angular.module("jsGen.router",[]).constant("app",{version:jsGenVersion}).provider("getFile",["app",function(a){this.html=function(b){return"/static/tpl/"+b+"?v="+(a.version||"")};this.md=function(b){return"/static/md/"+b+"?v="+(a.version||"")};this.$get=function(){return{html:this.html,md:this.md}}}]).config(["$routeProvider","$locationProvider","getFileProvider",function(a,b,c){b={templateUrl:c.html("index.html"),controller:"indexCtrl"};var d={templateUrl:c.html("login.html"),controller:"userLoginCtrl"},
f={templateUrl:c.html("register.html"),controller:"userRegisterCtrl"},e={templateUrl:c.html("user.html"),controller:"homeCtrl"},g={templateUrl:c.html("admin.html"),controller:"adminCtrl"},h={templateUrl:c.html("article-editor.html"),controller:"articleEditorCtrl"},k={templateUrl:c.html("index.html"),controller:"tagCtrl"},m={templateUrl:c.html("reset.html"),controller:"userResetCtrl"},l={templateUrl:c.html("user.html"),controller:"userCtrl"},p={templateUrl:c.html("article.html"),controller:"articleCtrl"};
c={templateUrl:c.html("collection.html"),controller:"collectionCtrl"};a.when("/hots",b).when("/update",b).when("/latest",b).when("/T:ID",b).when("/tag/:TAG",b).when("/login",d).when("/register",f).when("/reset",m).when("/home",e).when("/home/:OP",e).when("/admin",g).when("/admin/:OP",g).when("/tag",k).when("/add",h).when("/A:ID/edit",h).when("/user/U:ID",l).when("/user/U:ID/:OP",l).when("/U:ID",l).when("/U:ID/:OP",l).when("/A:ID",p).when("/C:ID",c).when("/",b).otherwise({redirectTo:"/"})}]);"use strict";
angular.module("jsGen.tools",[]).factory("tools",function(){function a(a){return Array.isArray&&Array.isArray(a)||"[object Array]"===Object.prototype.toString.call(a)}function b(a){return null===a||void 0===a||a!==a}function c(a){return b(a)?"":a+""}function d(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function f(a){for(var b in a)if(d(a,b))return!1;return!0}function e(b,c,f,e){c=c||angular.noop;if(b)if(a(b)){var g;if(e)for(e=b.length-1;0<=e&&c.call(f,b[e],e,b)!==m;e--);else for(e=0,g=
b.length;e<g&&c.call(f,b[e],e,b)!==m;e++);}else for(g in b)if(d(b,g)&&c.call(f,b[g],g,b)===m)break}function g(b){var c=typeof b;return null===b?"null":a(b)?"array":c}function h(a,b){var c=g(a);void 0===b&&(b=a,a="object"===c?{}:[]);c===g(b)&&("object"===c||"array"===c?e(b,function(b,c){var f=g(b);"object"===f||"array"===f?(a[c]=f===g(a[c])?a[c]:"object"===f?{}:[],h(a[c],b)):a[c]="function"===f?null:b}):a="function"===c?null:b);return a}function k(a,b){var c=g(a);if(c===g(b)&&("array"===c||"object"===
c))if(f(a))h(a,b);else if("array"===c&&1===a.length){var m=a[0],r=g(m);a.length=0;"function"!==r&&e(b,function(b){var c=g(b);if("null"===r||r===c)"object"===r||"array"===r?a.push(k(h(m),b)):a.push(h(b))})}else e(a,function(f,e){var m=g(f);"array"===c||d(b,e)?"function"===m&&"array"===c?a[e]=null:"null"===m?a[e]=h(b[e]):m===g(b[e])?"object"===m||"array"===m?k(a[e],b[e]):a[e]=b[e]:delete a[e]:delete a[e]});return a}var m={};return{trim:function(a){a=c(a);a=a.replace(/ +/g," ");a=a.replace(/^\s+/,"");
return a=a.replace(/\s+$/,"")},each:e,some:function(a,b,c){var f=!1,g=Array.prototype.some;b=b||angular.noop;if(a){if(g&&a.some===g)return a.some(b,c);e(a,function(a,e,g){if(f=b.call(c,a,e,g))return m});return!!f}return f},union:h,toStr:c,isNull:b,hasOwn:d,isEmpty:f,isArray:a,intersect:k,checkType:g,digestArray:function(b){var c=[];return a(b)?(e(b,function(a){"undefined"!==g(a)&&c.push(a)}),c):b}}});"use strict";
angular.module("jsGen.services",["ngResource","ngCookies"]).factory("timing",["$rootScope","$q","$exceptionHandler",function(a,b,c){function d(f,e,g){var d,k=0,m=b.defer(),l=m.promise;f=angular.isFunction(f)?f:angular.noop;e=parseInt(e,10);g=parseInt(g,10);g=0<=g?g:0;d=window.setInterval(function(){k+=1;if(g&&k>=g)window.clearInterval(d),m.resolve(f(k,g,e));else try{f(k,g,e)}catch(b){m.reject(b),c(b)}a.$$phase||a.$apply()},e);l.$timingId=d;return l}d.cancel=function(a){return a&&a.$timingId?(clearInterval(a.$timingId),
!0):!1};return d}]).factory("toast",["$log","tools",function(a,b){var c={};angular.forEach(["info","error","success","warning"],function(d){c[d]=function(c,e){var g=a[d]||a.log;e=b.toStr(e);g(c,e);c=angular.isObject(c)?angular.toJson(c):b.toStr(c);toastr[d](c,e)}});toastr.options=angular.extend({positionClass:"toast-bottom-full-width"},c.options);c.clear=toastr.clear;return c}]).factory("pretty",function(){return prettyPrint}).factory("param",function(){return $.param}).factory("CryptoJS",function(){return CryptoJS}).factory("utf8",
function(){return utf8}).factory("mdParse",["tools",function(a){return function(b){return marked(a.toStr(b))}}]).factory("sanitize",["tools",function(a){var b=Sanitize,c=b.Config,d=[new b({}),new b(c.RESTRICTED),new b(c.BASIC),new b(c.RELAXED)];return function(b,c){var g=document.createElement("div"),h=document.createElement("div");c=0<=c?c:3;g.innerHTML=a.toStr(b);h.appendChild(d[c].clean_node(g));return h.innerHTML}}]).factory("mdEditor",["mdParse","sanitize","pretty","tools",function(a,b,c,d){return function(f,
e){f=d.toStr(f);var g=new Markdown.Editor({makeHtml:function(c){return b(a(c),e)}},f),h=angular.element(document.getElementById("wmd-preview"+f));g.hooks.chain("onPreviewRefresh",function(){h.find("pre").addClass("prettyprint");c()});return g}}]).factory("restAPI",["$resource",function(a){return{index:a("/api/index/:OP"),user:a("/api/user/:ID/:OP"),article:a("/api/article/:ID/:OP"),tag:a("/api/tag/:ID/:OP")}}]).factory("cache",["$cacheFactory",function(a){return{user:a("user",{capacity:20}),article:a("article",
{capacity:100}),comment:a("comment",{capacity:500}),list:a("list",{capacity:100})}}]).factory("myConf",["$cookieStore","tools",function(a,b){function c(c,f){return function(e,g,h){g=b.toStr(g)+c;h=b.isNull(h)?f:h;var k;k=a.get(g);var m=h;k=b.isNull(k)?m:k;b.isNull(e)||k===(b.isNull(e)?h:e)||(a.put(g,e),k=e);return k}}return{pageSize:c("PageSize",10),listModel:c("ListModel",!1)}}]).factory("promiseGet",["$q",function(a){return function(b,c,d,f){var e,g=a.defer();(e=d&&f&&f.get(d))?g.resolve(e):c.get(b,
function(a){d&&f&&f.put(d,a);g.resolve(a)},function(a){g.reject(a.error)});return g.promise}}]).factory("getList",["restAPI","cache","promiseGet",function(a,b,c){return function(d){return c({ID:d,OP:10},a.article,d,b.list)}}]).factory("getArticle",["restAPI","cache","promiseGet",function(a,b,c){return function(d){return c({ID:d},a.article,d,b.article)}}]).factory("getUser",["restAPI","cache","promiseGet",function(a,b,c){return function(d){return c({ID:d},a.user,d,b.user)}}]).factory("getMarkdown",
["$http",function(a){return a.get("/static/md/markdown.md",{cache:!0})}]).factory("anchorScroll",function(){function a(a){a=$(a);var c=$(window),d=c.height(),f=a.offset().top;a=a.outerHeight();var c=c.scrollTop(),e=c+d;return f+(a>d?d:a)/2>c&&f+(a>d?d:a)/2<e?!0:a>d?f+a-d/2>c&&f+a-d/2<e:!1}return{toView:function(b,c,d){var f=$(window).height();b=$(b);d=0<d?d:f/10;$("html, body").animate({scrollTop:c?b.offset().top-d:b.offset().top+b.outerHeight()+d-f},{duration:200,easing:"linear",complete:function(){a(b)||
b[0].scrollIntoView(!!c)}})},inView:a}}).factory("applyFn",["$rootScope",function(a){return function(b,c){b=angular.isFunction(b)?b:angular.noop;c=c&&c.$apply?c:a;b();c.$$phase||c.$apply()}}]);"use strict";
angular.module("jsGen.filters",[]).filter("placeholder",["tools",function(a){return function(b){return a.toStr(b)||"-"}}]).filter("match",["$locale",function(a){return function(b,c){return a.FILTER[c]&&a.FILTER[c][b]||""}}]).filter("switch",["$locale",function(a){return function(b,c){return a.FILTER[c]&&a.FILTER[c][+!!b]||""}}]).filter("checkName",["tools",function(a){return function(b){b=a.toStr(b);return/^[(\u4e00-\u9fa5)a-z][(\u4e00-\u9fa5)a-zA-Z0-9_]{1,}$/.test(b)}}]).filter("length",["utf8",
"tools",function(a,b){return function(c){c=b.toStr(c);return a.stringToBytes(c).length}}]).filter("cutText",["utf8","tools",function(a,b){return function(c,d){c=b.toStr(c);c=c.replace(/\s+/g," ");var f=a.stringToBytes(c);d=d||0;f.length>d&&(f.length=d,c=a.bytesToString(f),c=c.slice(0,-2)+"\u2026");return c}}]).filter("formatDate",["$filter","$locale",function(a,b){return function(c,d){var f=Date.now()-c,e=a("date");return d?e(c,b.DATETIME.full):2592E5<f?e(c,b.DATETIME["short"]):864E5<f?Math.floor(f/
864E5)+b.DATETIME.dayAgo:36E5<f?Math.floor(f/36E5)+b.DATETIME.hourAgo:6E4<f?Math.floor(f/6E4)+b.DATETIME.minuteAgo:b.DATETIME.secondAgo}}]).filter("formatTime",["$locale",function(a){return function(b){function c(a){f=e%a;return e=(e-f)/a}var d="",f=0,e=0<b?Math.round(b):Math.floor(Date.now()/1E3);b=a.DATETIME;c(60);d=f+b.second;c(60);d=(0<f?f+b.minute:"")+d;c(24);d=(0<f?f+b.hour:"")+d;return 0<e?e+b.day+d:d}}]).filter("formatBytes",["$locale",function(a){return function(a){return(a=0<a?a:0)?1024>
a?a+"B":1048576>a?(a/1024).toFixed(3)+" KiB":1073741824>a?(a/1048576).toFixed(3)+" MiB":(a/1073741824).toFixed(3)+" GiB":"-"}}]);"use strict";
angular.module("jsGen.directives",[]).directive("genParseMd",["mdParse","sanitize","pretty",function(a,b,c){return function(d,f,e){d.$watch(e.genParseMd,function(e){e||0===e?(e=a(e),e=b(e),f.html(e),f.find("pre").addClass("prettyprint"),f.find("a").attr("target",function(){if(this.host!==location.host)return"_blank"}),c()):f.html("")})}}]).directive("genTabClick",function(){return{link:function(a,b,c){var d=c.genTabClick;b.bind("click",function(){b.parent().children().removeClass(d);b.addClass(d)})}}}).directive("genPagination",
["getFile",function(a){return{scope:!0,templateUrl:a.html("gen-pagination.html"),link:function(a,c,d){a.$watchCollection(d.genPagination,function(c,e){if(angular.isObject(c)){var d=1,h=[],k=Math.ceil(c.total/c.pageSize)||1,d=1<=c.pageIndex?c.pageIndex:1,d=d<=k?d:k;h[0]=d;if(6>=d)for(;1<h[0];)h.unshift(h[0]-1);else h.unshift(h[0]-1),h.unshift(h[0]-1),h.unshift("\u2026"),h.unshift(2),h.unshift(1);if(5>=k-d)for(;h[h.length-1]<k;)h.push(h[h.length-1]+1);else h.push(h[h.length-1]+1),h.push(h[h.length-
1]+1),h.push("\u2026"),h.push(k-1),h.push(k);a.prev=1<d?d-1:0;a.next=d<k?d+1:0;a.total=c.total;a.pageIndex=d;a.showPages=h;a.pageSize=c.pageSize;a.perPages=c.sizePerPage||[10,20,50];a.path=c.path&&c.path+"?p="}});a.paginationTo=function(c,e){!a.path&&0<c&&(e=e||a.pageSize,a.$emit("genPagination",c,e))}}}}]).directive("genModalMsg",["getFile","$timeout",function(a,b){var c=0;return{scope:!0,transclude:!0,templateUrl:a.html("gen-modal.html"),link:function(a,f,e){function g(a){return function(){var b=
t(a)?a():!0;k(!b)}}function h(){var a=l.children(),b=0.382*($(window).height()-a.outerHeight()),c={};c.top=0<b?b:0;0<n.width&&(c.width=n.width,c.marginLeft=-n.width/2);a.css(c)}function k(a){l.modal(a?"show":"hide");a&&b(h)}var m,l=f.children(),p=["Confirm","Cancel","Delete"],n=a.$eval(e.genModalMsg),t=angular.isFunction;f.is(":visible")&&(n.cancelFn=n.cancelFn||!0,n.backdrop=n.backdrop||"static",n.show=n.show||!1,n.modal=k,a.$watch(function(){return n},function(b){angular.extend(a,b)},!0),a.id=a.id||
e.genModalMsg+"-"+c++,angular.forEach(p,function(b){var c=b.toLowerCase(),e=c+"Fn",f=c+"Btn";a[c+"Cb"]=n[e]&&g(n[e]);a[f]=n[f]||n[e]&&b}),l.on("shown.bs.modal",function(a){a.stopPropagation();m=!0}),l.on("hidden.bs.modal",function(a){a.stopPropagation();m&&t(n.cancelFn)&&n.cancelFn();m=!1}),l.modal(n))}}}]).directive("genTooltip",["$timeout",function(a){return{require:"?ngModel",link:function(b,c,d,f){function e(a){f.validate=m&&l.validate&&c.is(":visible");if(f.validate){var b=f.$name&&f.$name+" "||
"";a&&l.validateMsg&&angular.forEach(f.$error,function(a,c){b+=a&&l.validateMsg[c]&&l.validateMsg[c]+", "||""});b=b.slice(0,-2)||d.originalTitle||d.title;d.$set("dataOriginalTitle",b?b:"");k(!!a)}else k(!1)}function g(b){a(function(){e(f.$invalid)});return b}function h(){c.off(".tooltip").removeData("tooltip");c.tooltip(l)}function k(a){c.hasClass("invalid-error")!==a&&(c[a?"addClass":"removeClass"]("invalid-error"),c.tooltip(a?"show":"hide"))}var m=!1,l=b.$eval(d.genTooltip)||{};"inner"===l.container?
l.container=c:"ngView"===l.container&&(l.container=c.parents(".ng-view")[0]||c.parents("[ng-view]")[0]);l.validate?(l.template='<div class="tooltip validate-tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',l.trigger="manual",l.placement=l.placement||"right",f?(f.$formatters.push(g),f.$parsers.push(g)):b.$watch(function(){return d.originalTitle||d.dataOriginalTitle},k),b.$on("genTooltipValidate",function(a,b,c){m=!c;f&&(angular.isArray(b)&&b.push(f),e(f.$invalid))})):
l.click&&c.bind("click",function(){c.tooltip(l.click)});c.bind("hidden.bs.tooltip",h);h()}}}]).directive("genXeditable",["getFile",function(a){return{scope:{value:"=genXeditable"},templateUrl:a.html("gen-xeditable.html"),link:function(a,c,d){var f;c.bind("click",function(){f=a.value;a.isEdit=!0});a.save=function(){a.placeholder=!a.value;a.isEdit=!1;d.save&&a.$parent.$eval(d.save)};a.cancel=function(){a.value=f;a.isEdit=!1};c.addClass("gen-xeditable");a.placeholder=!a.value;a.isEdit=!1}}}]).directive("genMoving",
["anchorScroll",function(a){return{link:function(b,c,d){function f(){var a=c.find("textarea");a.is(a)&&a.css({height:"auto",width:"100%"})}b=b.$eval(d.genMoving);b.appendTo=function(a){c.appendTo($(a));f()};b.prependTo=function(a){c.prependTo($(a));f()};b.childrenOf=function(a){return $(a).find(c).is(c)};b.scrollIntoView=function(b,d){a.toView(c,b,d)};b.inView=function(){return a.inView(c)}}}}]).directive("genSrc",function(){return{priority:99,link:function(a,b,c){c.$observe("genSrc",function(a){if(a){var b=
new Image;b.onload=function(){c.$set("src",a)};b.src=a}})}}});"use strict";
angular.module("jsGen.controllers",["ui.validate"]).controller("indexCtrl",["app","$scope","$routeParams","getList",function(a,b,c,d){function f(){var d={ID:e,p:c.p,s:c.s||h.pageSize(null,"index",10)};a.promiseGet(d,g,a.param(d),a.cache.list).then(function(c){var e=c.pagination||{};c.tag&&(b.other.title=c.tag.tag,b.other._id=c.tag._id);e.path=a.location.path();e.pageSize=h.pageSize(e.pageSize,"index");b.pagination=e;b.articleList=c.data})}var e="",g=a.restAPI.article,h=a.myConf,k=a.rootScope.global;
k.title2=k.description;b.parent={getTpl:a.getFile.html("index-article.html"),viewPath:"latest",listModel:h.listModel(k.isPhone||null,"index",!1)};b.other={};b.pagination={};b.setListModel=function(){var a=b.parent;a.listModel=h.listModel(!a.listModel,"index");h.pageSize(a.listModel?20:10,"index");f()};(function(){var d=a.location.path().slice(1).split("/");c.TAG||/^T[0-9A-Za-z]{3,}$/.test(d[0])?(g=a.restAPI.tag,b.other._id=d[0],b.other.title=c.TAG||d[0],b.parent.viewPath=""):(g=a.restAPI.article,
b.parent.viewPath=d[0]||"latest");e=c.TAG||d[0]})();f();d("comment").then(function(c){c=c.data;a.each(c,function(b,c){b.content=a.filter("cutText")(b.content,180)});b.hotComments=c.slice(0,5)})}]).controller("tagCtrl",["app","$scope","$routeParams","getList",function(a,b,c,d){var f=a.restAPI.tag,e=a.myConf;c={p:c.p,s:c.s||e.pageSize(null,"tag",50)};a.rootScope.global.title2=a.locale.TAG.title;b.parent={getTpl:a.getFile.html("index-tag.html")};b.pagination={};a.promiseGet(c,f,a.param(c),a.cache.list).then(function(c){var d=
c.pagination||{};d.path=a.location.path();d.pageSize=e.pageSize(d.pageSize,"tag");d.sizePerPage=[50,100,200];b.pagination=d;b.tagList=c.data});d("comment").then(function(c){c=c.data;a.each(c,function(b,c){b.content=a.filter("cutText")(b.content,180)});b.hotComments=c.slice(0,5)})}]).controller("userLoginCtrl",["app","$scope",function(a,b){a.clearUser();a.rootScope.global.title2=a.locale.USER.login;b.login={logauto:!0,logname:"",logpwd:""};b.reset={title:"",type:""};b.submit=function(){if(a.validate(b)){var c=
a.union(b.login);c.logtime=Date.now()-a.timeOffset;c.logpwd=a.CryptoJS.SHA256(c.logpwd).toString();c.logpwd=a.CryptoJS.HmacSHA256(c.logpwd,c.logname+":"+c.logtime).toString();a.restAPI.user.save({ID:"login"},c,function(c){a.rootScope.global.user=c.data;a.checkUser();b.$destroy();a.location.path("/home")},function(c){b.reset.type=c.error.name;b.reset.title=a.locale.RESET[c.error.name]})}}}]).controller("userResetCtrl",["app","$scope","$routeParams",function(a,b,c){function d(){b.timingModal.modal(!0);
f=a.timing(function(a,c){b.parent.timing=c-a},1E3,b.parent.timing);f.then(function(){b.timingModal.modal(!1);a.location.search({}).path("/")})}var f,e=a.locale;a.rootScope.global.title2=e.USER.reset;b.reset={name:"",email:"",request:c.req};b.parent={title:e.RESET[c.req],timing:5};b.timingModal={confirmBtn:e.BTN_TEXT.goBack,confirmFn:function(){a.timing.cancel(f);a.timing(null,100,1).then(function(){a.location.search({}).path("/")});return!0},cancelBtn:e.BTN_TEXT.cancel,cancelFn:function(){return a.timing.cancel(f)}};
b.submit=function(){a.validate(b)&&a.restAPI.user.save({ID:"reset"},b.reset,function(b){a.toast.success(e.RESET.email,e.RESPONSE.success);d()})};0>["locked","passwd"].indexOf(c.req)&&a.restAPI.user.get({ID:"reset",OP:c.req},function(){a.toast.success(3+e.TIMING.goHome,e.RESPONSE.success);a.timing(null,1E3,3).then(function(){a.location.search({}).path("/home")})},d)}]).controller("userRegisterCtrl",["app","$scope",function(a,b){var c=a.filter,d=c("length"),f=a.rootScope.global;a.clearUser();f.title2=
a.locale.USER.register;b.user={name:"",email:"",passwd:"",passwd2:""};b.checkName=function(a,b){return c("checkName")(b.$value)};b.checkMin=function(a,b){return 5<=d(b.$value)};b.checkMax=function(a,b){return 15>=d(b.$value)};b.submit=function(){var c=b.user;if(a.validate(b)){var d={name:c.name,email:c.email};d.passwd=a.CryptoJS.SHA256(c.passwd).toString();a.restAPI.user.save({ID:"register"},d,function(c){a.rootScope.global.user=c.data;a.checkUser();b.$destroy();a.location.path("/home")})}}}]).controller("homeCtrl",
["app","$scope","$routeParams",function(a,b,c){var d=a.rootScope.global;if(!d.isLogin)return a.location.search({}).path("/");d.title2=a.locale.HOME.title;b.user=d.user;b.parent={getTpl:a.getFile.html(function(a){switch(a){case "follow":case "fans":return"user-list.html";case "detail":return"user-edit.html";case "article":case "comment":case "mark":return"user-article.html";default:return"user-article.html"}}(c.OP)),isMe:!0,viewPath:c.OP||"index"}}]).controller("userCtrl",["app","$scope","$routeParams",
"getUser",function(a,b,c,d){a.rootScope.global.title2=a.locale.USER.title;b.parent={getTpl:a.getFile.html(function(){switch(c.OP){case "fans":return"user-list.html";case "article":return"user-article.html";default:return"user-article.html"}}()),isMe:!1,viewPath:c.OP||"index"};d("U"+c.ID).then(function(c){b.user=c.data;a.rootScope.global.title2=b.user.name+a.locale.USER.title})}]).controller("userListCtrl",["app","$scope","$routeParams",function(a,b,c){var d=a.restAPI.user,f=a.myConf,e=a.locale,g=
{ID:c.ID&&"U"+c.ID||c.OP,OP:c.OP||"fans",p:c.p,s:c.s||f.pageSize(null,"user",20)};b.parent={title:""};a.promiseGet(g,d,a.param(g),a.cache.list).then(function(d){var k=d.pagination||{};k.path=a.location.path();k.pageSize=f.pageSize(k.pageSize,"user");b.pagination=k;a.each(d.data,function(b){a.checkFollow(b)});b.parent.title=c.ID?d.user.name+e.USER[g.OP]:e.HOME[g.OP];b.userList=d.data})}]).controller("userArticleCtrl",["app","$scope","$routeParams",function(a,b,c){function d(){var d={ID:c.ID&&"U"+c.ID||
c.OP,OP:c.OP||(c.ID?"article":"index"),p:c.p,s:c.s||e.pageSize(null,"home",10)};a.promiseGet(d,f,a.param(d),a.cache.list).then(function(f){var l=0,p=f.pagination||{};p.path=a.location.path();p.pageSize=e.pageSize(p.pageSize,"home");b.pagination=p;if(c.ID)b.parent.title=f.user.name+g.USER[d.OP];else{var n=h.user||{};a.each(f.data,function(a){0<f.readtimestamp&&(a.read=a.updateTime<f.readtimestamp,l+=!a.read);a.isAuthor=a.author._id===n._id});b.parent.title="index"!==d.OP?g.HOME[d.OP]:l+g.HOME.index+
a.filter("date")(f.readtimestamp,"medium")}b.articleList=f.data})}var f=a.restAPI.user,e=a.myConf,g=a.locale,h=a.rootScope.global;b.parent={listModel:e.listModel(h.isPhone||null,"index",!1),title:""};b.pagination={};b.removeArticle=null;b.removeArticleModal={confirmBtn:g.BTN_TEXT.confirm,confirmFn:function(){var c=b.removeArticle;a.restAPI.article.remove({ID:c._id},function(){a.some(b.articleList,function(b,d,e){if(b._id===c._id)return e.splice(d,1),a.toast.success(g.ARTICLE.removed+c.title,g.RESPONSE.success),
!0});b.removeArticle=null});return!0},cancelBtn:g.BTN_TEXT.cancel,cancelFn:function(){b.removeArticle=null;return!0}};b.setListModel=function(){var a=b.parent;a.listModel=e.listModel(!a.listModel,"home");e.pageSize(a.listModel?20:10,"home");d()};b.remove=function(a){a.isAuthor&&(b.removeArticle=a,b.removeArticleModal.modal(!0))};d()}]).controller("userEditCtrl",["app","$scope",function(a,b){function c(){d=a.union(g.user);a.each(d.tagsList,function(a,b,c){c[b]=a.tag});d=a.intersect(a.union(k),d);b.user=
a.union(d);a.checkDirty(k,d,b.user)}var d={},f=a.locale,e=a.filter,g=a.rootScope.global,h=e("length"),k={avatar:"",name:"",sex:"",email:"",desc:"",passwd:"",tagsList:[""]};b.sexArray=["male","female"];b.checkName=function(a,b){return e("checkName")(b.$value)};b.checkMin=function(a,b){return 5<=h(b.$value)};b.checkMax=function(a,b){return 15>=h(b.$value)};b.checkDesc=function(a,b){return h(b.$value)<=g.SummaryMaxLen};b.checkTag=function(a,b){var c=b.$value||"",c=angular.isString(c)?c.split(/[,\uff0c\u3001]/):
c;return c.length<=g.UserTagsMax};b.getTag=function(a){var c=b.user.tagsList;0>c.indexOf(a.tag)&&c.length<g.UserTagsMax&&(b.user.tagsList=c.concat(a.tag))};b.reset=function(){b.user=a.union(d)};b.verifyEmail=function(){a.restAPI.user.save({ID:"reset"},{request:"role"},function(){a.toast.success(f.RESET.email,f.RESPONSE.success)})};b.submit=function(){var e=a.union(b.user);a.validate(b)&&(e=a.checkDirty(k,d,e),a.isEmpty(e)?a.toast.info(f.USER.noUpdate):(e.passwd&&(e.passwd=a.CryptoJS.SHA256(e.passwd).toString()),
e.email&&(a.restAPI.user.save({ID:"reset"},{email:e.email,request:"email"},function(){a.toast.success(f.USER.email,f.RESPONSE.success)}),delete e.email),a.isEmpty(e)?c():a.restAPI.user.save({},e,function(b){a.union(g.user,b.data);c();a.toast.success(f.USER.updated,f.RESPONSE.success)})))};b.$watchCollection("user",function(b){a.checkDirty(k,d,b)});c()}]).controller("articleCtrl",["app","$scope","$routeParams","mdEditor","getList","getMarkdown",function(a,b,c,d,f,e){function g(b){var c=s._id;angular.isObject(b)&&
(b.isAuthor=c===b.author._id,b.isMark=a.some(b.markList,function(a){return a._id===c}),b.isFavor=a.some(b.favorsList,function(a){return a._id===c}),b.isOppose=a.some(b.opposesList,function(a){return a._id===c}),a.each(b.commentsList,function(a){g(a)}))}function h(){n.isLogin||a.toast.error(p.USER.noLogin);return n.isLogin}function k(){var a=b.comment,c=b.article;a.replyToComment="";a.title="\u8bc4\u8bba\uff1a"+r(c.title,n.TitleMaxLen-9);a.content="";a.refer=c._id;b.replyMoving.prependTo("#comments")}
var m="A"+c.ID,l=a.myConf,p=a.locale,n=a.rootScope.global;c=a.filter;var t=c("length"),r=c("cutText"),u=a.cache.comment,x=a.cache.list,v=a.restAPI.article,s=n.user||{},s={_id:s._id,name:s.name,avatar:s.avatar};b.parent={wmdPreview:!1,contentBytes:0,markdownHelp:""};b.comment={title:"",content:"",refer:"",replyToComment:""};b.replyMoving={};b.commentMoving={};b.markdownModal={title:p.ARTICLE.markdown,cancelBtn:p.BTN_TEXT.goBack,width:720};b.validateTooltip=a.union(a.rootScope.validateTooltip);b.validateTooltip.placement=
"bottom";b.wmdHelp=function(){e.success(function(a){b.parent.markdownHelp=a;b.markdownModal.modal(!0)})};b.wmdPreview=function(){b.parent.wmdPreview=!b.parent.wmdPreview;b.replyMoving.scrollIntoView(!0)};b.checkContentMin=function(a,c){var d=t(c.$value);b.parent.contentBytes=d;return d>=n.ContentMinLen};b.checkContentMax=function(a,b){return t(b.$value)<=n.ContentMaxLen};b.reply=function(c){var d=b.comment;d.refer=c._id;b.parent.wmdPreview=!1;c._id===b.article._id?k():(d.replyToComment=c._id,d.title=
p.ARTICLE.reply+r(a.sanitize(a.mdParse(c.content),0),n.TitleMaxLen-9),b.replyMoving.appendTo("#"+c._id));b.replyMoving.scrollIntoView()};b.getComments=function(c,d){function e(){var b=[];a.each(c,function(a){h[a]&&b.push(h[a])});return b}var f=[],h={};b.referComments=[];d&&(c&&0<c.length)&&(b.commentMoving.childrenOf("#"+d._id)?b.commentMoving.appendTo("#comments"):(b.commentMoving.appendTo("#"+d._id),a.each(c,function(a){var b=u.get(a);b?h[a]=b:f.push(a)}),b.referComments=e(),0<f.length&&v.save({ID:"comment"},
{data:f},function(c){a.each(c.data,function(a){g(a);u.put(a._id,a);h[a._id]=a});b.referComments=e()})))};b.highlight=function(a){a.status=2===a.status?1:2};b.setMark=function(b){h()&&v.save({ID:b._id,OP:"mark"},{mark:!b.isMark},function(){b.isMark=!b.isMark;b.isMark?b.markList.push(s):a.removeItem(s,"_id",b.markList);a.toast.success(p.ARTICLE[b.isMark?"marked":"unmarked"])})};b.setFavor=function(b){h()&&v.save({ID:b._id,OP:"favor"},{favor:!b.isFavor},function(){b.isFavor=!b.isFavor;b.isFavor?(b.favorsList.push(s),
a.removeItem(s,"_id",b.opposesList),b.isOppose=!1):a.removeItem(s,"_id",b.favorsList);a.toast.success(p.ARTICLE[b.isFavor?"favored":"unfavored"])})};b.setOppose=function(b){h()&&v.save({ID:b._id,OP:"oppose"},{oppose:!b.isOppose},function(){b.isOppose=!b.isOppose;b.isOppose?(b.opposesList.push(s),a.removeItem(s,"_id",b.favorsList),b.isFavor=!1):a.removeItem(s,"_id",b.opposesList);a.toast.success(p.ARTICLE[b.isOppose?"opposed":"unopposed"])})};b.submit=function(){if(h()&&a.validate(b)){var c=a.union(b.comment),
d=b.article;v.save({ID:d._id,OP:"comment"},c,function(c){var e=c.data,f=b.comment.replyToComment;d.commentsList.unshift(e);d.comments+=1;d.updateTime=Date.now();f&&a.some(d.commentsList,function(a,b){if(f===a._id)return d.commentsList[b].commentsList.push(e._id),!0});u.put(e._id,e);k()})}};b.$on("genPagination",function(c,d,e){c.stopPropagation();c={ID:m,OP:"comment",p:d,s:l.pageSize(e,"comment",10)};a.promiseGet(c,v,a.param(c),x).then(function(c){var d=c.pagination||{};c=c.data;d.pageSize=l.pageSize(d.pageSize,
"comment");b.pagination=d;a.each(c,function(a){g(a);u.put(a._id,a)});b.article.commentsList=c;a.anchorScroll.toView("#comments",!0)})});d().run();a.promiseGet({ID:m},v,m,a.cache.article).then(function(c){var d=c.pagination||{};c=c.data;d.pageSize=l.pageSize(d.pageSize,"comments");g(c);a.each(c.commentsList,function(a){u.put(a._id,a)});n.title2=c.title;b.pagination=d;b.article=c;k();a.promiseGet({ID:c.author._id,OP:"article"},a.restAPI.user,c.author._id,x).then(function(c){var d=c.user,e=b.article.author;
a.checkFollow(d);a.union(e,d);e.articlesList=c.data})});f("hots").then(function(a){b.hotArticles=a.data.slice(0,10)})}]).controller("articleEditorCtrl",["app","$scope","$routeParams","mdEditor","getMarkdown",function(a,b,c,d,f){function e(c){u=a.union(r);c&&(c=a.union(c),a.each(c.tagsList,function(a,b,c){c[b]=a.tag}),c.refer=c.refer&&c.refer.url,a.intersect(u,c));b.article=a.union(u);a.checkDirty(r,u,b.article);g(c)}function g(a){var c=b.parent,d=b.article;a?(c.title=m.ARTICLE.preview+k(d.title),
c.content=d.content):f.success(function(a){c.title=m.ARTICLE.markdown;c.content=a})}var h=c.ID&&"A"+c.ID,k=a.toStr,m=a.locale,l=a.rootScope.global;c=a.filter;var p=c("length");c("cutText");var n=a.restAPI.article,t=a.cache.article,r={title:"",content:"",refer:"",tagsList:[]},u=a.union(r);l.isLogin||a.location.search({}).path("/");l.title2=a.locale.ARTICLE.title;b.parent={edit:!!h,wmdPreview:!0,contentBytes:0,titleBytes:0,title:"",content:""};b.validateTooltip=a.union(a.rootScope.validateTooltip);
b.validateTooltip.placement="bottom";b.checkTitleMin=function(c,d){var e=p(d.$value);b.parent.titleBytes=e;b.parent.wmdPreview&&(b.parent.title=m.ARTICLE.preview+a.sanitize(a.trim(d.$value),0));return e>=l.TitleMinLen};b.checkTitleMax=function(a,b){return p(b.$value)<=l.TitleMaxLen};b.checkContentMin=function(a,c){var d=p(c.$value);b.parent.contentBytes=d;b.parent.wmdPreview&&(b.parent.content=c.$value);return d>=l.ContentMinLen};b.checkContentMax=function(a,b){return p(b.$value)<=l.ContentMaxLen};
b.checkTag=function(a,b){var c=b.$value||"",c=angular.isString(c)?c.split(/[,\uff0c\u3001]/):c;return c.length<=l.ArticleTagsMax};b.getTag=function(a){var c=b.article.tagsList;0>c.indexOf(a.tag)&&c.length<l.ArticleTagsMax&&(b.article.tagsList=c.concat(a.tag))};b.wmdPreview=function(){var a=b.parent;a.wmdPreview=!a.wmdPreview;g(a.wmdPreview)};b.submit=function(){var c=a.union(b.article);a.validate(b)&&(a.checkDirty(r,u,c)?(c.title=a.sanitize(a.trim(c.title),0),n.save({ID:h||"index",OP:h&&"edit"},c,
function(b){var c=b.data;t.put(c._id,b);e(c);a.toast.success(m.ARTICLE[h?"updated":"added"]+c.title);a.timing(null,1E3,2).then(function(){a.location.search({}).path("/"+c._id)})})):a.toast.info(m.ARTICLE.noUpdate))};b.$watchCollection("article",function(b){a.checkDirty(r,u,b)});d().run();h?a.promiseGet({ID:h},n,h,t).then(function(a){e(a.data)}):e()}]).controller("adminCtrl",["app","$scope","$routeParams",function(a,b,c){var d=a.rootScope.global;c=c.OP||"index";if(!d.isEditor)return a.location.search({}).path("/");
b.parent={getTpl:a.getFile.html(function(a){return"admin-"+("comment"===a?"article":a)+".html"}(c)),viewPath:c};d.title2=a.locale.ADMIN[c]}]).controller("adminUserCtrl",["app","$scope","$routeParams",function(a,b,c){function d(c){f=a.union(a.union(k),c);b.userList=a.union(f);b.parent.editSave=!!a.checkDirty(k,f,b.userList)}var f={},e=a.restAPI.user,g=a.myConf,h=a.locale;c={ID:"admin",p:c.p,s:c.s||g.pageSize(null,"userAdmin",50)};var k=[{_id:"",name:"",locked:!1,email:"",role:0,score:0,date:0,lastLoginDate:0}];
b.parent={editSave:!1,isSelectAll:!1};b.pagination={};b.roleArray=[0,1,2,3,4,5];b.selectAll=function(){a.each(b.userList,function(a){a.isSelect=b.parent.isSelectAll})};b.reset=function(){b.userList=a.union(f)};b.submit=function(){var c=[{_id:"",locked:!1,role:0}];if(a.validate(b)){var g=a.checkDirty(k,f,b.userList);a.isEmpty(g)?a.toast.info(h.USER.noUpdate):(g=a.intersect(c,g),e.save({ID:"admin"},{data:g},function(c){var e=[];a.each(g,function(d){var f=c.data[d._id];a.some(b.tagList,function(b,c,
h){if(d._id===b._id)return f?(a.union(b,f),e.push(f.tag)):h.splice(c,1),!0})});d(b.userList);a.toast.success(h.USER.updated+e.join(", "),h.RESPONSE.success)}))}};b.$watch("userList",function(c){b.parent.editSave=!!a.checkDirty(k,f,c)},!0);a.promiseGet(c,e).then(function(c){var e=c.pagination||{};e.path=a.location.path();e.pageSize=g.pageSize(e.pageSize,"userAdmin");e.sizePerPage=[50,100,200];b.pagination=e;d(c.data)})}]).controller("adminTagCtrl",["app","$scope","$routeParams",function(a,b,c){function d(c){f=
a.union(a.union(k),c);b.tagList=a.union(f);b.parent.editSave=!!a.checkDirty(k,f,b.tagList)}var f={},e=a.restAPI.tag,g=a.myConf,h=a.locale;c={ID:"index",p:c.p,s:c.s||g.pageSize(null,"tagAdmin",20)};var k=[{_id:"",articles:0,tag:"",users:0}];b.parent={editSave:!1};b.pagination={};b.removeTag=null;b.removeTagModal={confirmBtn:h.BTN_TEXT.confirm,confirmFn:function(){var c=b.removeTag;e.remove({ID:c._id},function(){a.some(b.tagList,function(b,d,e){if(b._id===c._id)return e.splice(d,1),a.toast.success(h.TAG.removed+
c.tag,h.RESPONSE.success),!0});d(b.tagList);b.removeTag=null});return!0},cancelBtn:h.BTN_TEXT.cancel,cancelFn:function(){b.removeTag=null;return!0}};b.checkTag=function(b,c){var d=a.toStr(c.$value);return!/[,\uff0c\u3001]/.test(d)};b.checkTagMin=function(b,c){return 3<=a.filter("length")(c.$value)};b.reset=function(){b.tagList=a.union(f)};b.remove=function(a){b.removeTag=a;b.removeTagModal.modal(!0)};b.submit=function(){var c=[{_id:"",tag:""}];if(a.validate(b)){var g=a.checkDirty(k,f,b.tagList);a.isEmpty(g)?
a.toast.info(h.TAG.noUpdate):(g=a.intersect(c,g),e.save({ID:"admin"},{data:g},function(c){var e=[];a.each(g,function(d){var f=c.data[d._id];a.some(b.tagList,function(b,c,h){if(d._id===b._id)return f?(a.union(b,f),e.push(f.tag)):h.splice(c,1),!0})});d(b.tagList);a.toast.success(h.TAG.updated+e.join(", "),h.RESPONSE.success)}))}};b.$watch("tagList",function(c){b.parent.editSave=!!a.checkDirty(k,f,c)},!0);a.promiseGet(c,e).then(function(b){var c=b.pagination||{};c.path=a.location.path();c.pageSize=g.pageSize(c.pageSize,
"tagAdmin");c.sizePerPage=[20,50,100];d(b.data)})}]).controller("adminArticleCtrl",["app","$scope",function(a,b){}]).controller("adminGlobalCtrl",["app","$scope",function(a,b){var c={},d=a.filter,f=a.restAPI.index;d("length");b.parent={switchTab:"tab1"};b.setClass=function(a){return a?"btn-warning":"btn-success"};b.reset=function(){b.global=a.union(c);b.editSave=!1};b.submit=function(){var d=a.union(b.global);b.editSave=!1;angular.forEach(d.UsersScore,function(a,b){d.UsersScore[b]=+a});angular.forEach(d.ArticleStatus,
function(a,b){d.ArticleStatus[b]=+a});angular.forEach(d.ArticleHots,function(a,b){d.ArticleHots[b]=+a});angular.forEach(d.paginationCache,function(a,b){d.paginationCache[b]=+a});angular.forEach(d,function(a,b){angular.equals(a,c[b])&&delete d[b]});var f=a.restAPI.index.save({OP:"admin"},d,function(){if(f.err)a.rootScope.msg=f.err;else{b.global=a.union(f);c=a.union(f);var d=a.union(b.global);a.intersect(d,b.global);a.union(b.global,d);a.rootScope.msg={name:"\u8bf7\u6c42\u6210\u529f",message:"\u4fee\u6539\u6210\u529f\uff01"}}})};
a.promiseGet({OP:"admin"},f).then(function(d){c=a.union(d.data);b.global=a.union(c)})}]);"use strict";
angular.module("jsGen.locale",["ngLocale"]).run(["$locale",function(a){angular.extend(a,{RESET:{locked:"\u7533\u8bf7\u89e3\u9501",passwd:"\u627e\u56de\u5bc6\u7801",email:"\u8bf7\u6c42\u4fe1\u606f\u5df2\u53d1\u9001\u5230\u60a8\u7684\u90ae\u7bb1\uff0c\u8bf7\u67e5\u6536\u3002"},RESPONSE:{success:"\u8bf7\u6c42\u6210\u529f",error:"\u8bf7\u6c42\u5931\u8d25"},VALIDATE:{required:"\u5fc5\u586b\uff01",minlength:"\u592a\u77ed\uff01",maxlength:"\u592a\u957f\uff01",min:"\u592a\u5c0f\uff01",max:"\u592a\u5927\uff01",
more:"\u592a\u591a\uff01",email:"Email\u65e0\u6548\uff01",pattern:"\u683c\u5f0f\u65e0\u6548\uff01",username:"\u6709\u6548\u5b57\u7b26\u4e3a\u6c49\u5b57\u3001\u5b57\u6bcd\u3001\u6570\u5b57\u3001\u4e0b\u5212\u7ebf\uff0c\u4ee5\u6c49\u5b57\u6216\u5c0f\u5199\u5b57\u6bcd\u5f00\u5934\uff01",minname:"\u957f\u5ea6\u5e94\u5927\u4e8e5\u5b57\u8282\uff0c\u4e00\u4e2a\u6c49\u5b573\u5b57\u8282\uff01",maxname:"\u957f\u5ea6\u5e94\u5c0f\u4e8e15\u5b57\u8282\uff0c\u4e00\u4e2a\u6c49\u5b573\u5b57\u8282\uff01",repasswd:"\u5bc6\u7801\u4e0d\u4e00\u81f4\uff01",
url:"URL\u65e0\u6548\uff01",tag:"\u6807\u7b7e\u9519\u8bef\uff0c\u4e0d\u80fd\u5305\u542b\u201c,\u201d\u3001\u201c\uff0c\u201d\u548c\u201c\u3001\u201d"},BTN_TEXT:{confirm:"\u786e\u5b9a",cancel:"\u53d6\u6d88",remove:"\u5220\u9664",goBack:"\u8fd4\u56de"},TIMING:{goHome:"\u79d2\u949f\u540e\u81ea\u52a8\u8fd4\u56de\u4e3b\u9875"},HOME:{title:"\u6211\u7684\u4e3b\u9875",index:" \u66f4\u65b0\uff0c\u9605\u8bfb\u65f6\u95f4\u7ebf\uff1a",mark:"\u6211\u7684\u6536\u85cf",article:"\u6211\u7684\u6587\u7ae0",comment:"\u6211\u7684\u8bc4\u8bba",
follow:"\u6211\u7684\u5173\u6ce8",fans:"\u6211\u7684\u7c89\u4e1d"},ADMIN:{index:"\u7f51\u7ad9\u4fe1\u606f",user:"\u7528\u6237\u7ba1\u7406",tag:"\u6807\u7b7e\u7ba1\u7406",article:"\u6587\u7ae0\u7ba1\u7406",comment:"\u8bc4\u8bba\u7ba1\u7406",message:"\u6d88\u606f\u7ba1\u7406",global:"\u7f51\u7ad9\u8bbe\u7f6e"},ARTICLE:{title:"\u6dfb\u52a0/\u7f16\u8f91\u6587\u7ae0",preview:"\u9884\u89c8\uff1a",reply:"\u8bc4\u8bba\uff1a",removed:"\u6210\u529f\u5220\u9664 ",updated:"\u6210\u529f\u66f4\u65b0 ",noUpdate:"\u6587\u7ae0\u6682\u65e0\u53d8\u66f4",
added:"\u6210\u529f\u4fdd\u5b58 ",markdown:"Markdown\u7b80\u660e\u8bed\u6cd5",marked:"\u5df2\u6536\u85cf ",unmarked:"\u5df2\u53d6\u6d88\u6536\u85cf ",favored:"\u5df2\u652f\u6301 ",unfavored:"\u5df2\u53d6\u6d88\u652f\u6301 ",opposed:"\u5df2\u53cd\u5bf9 ",unopposed:"\u5df2\u53d6\u6d88\u53cd\u5bf9 ",highlight:"\u7f6e\u9876 ",unhighlight:"\u53d6\u6d88\u7f6e\u9876 "},USER:{title:"\u7684\u4e3b\u9875",login:"\u7528\u6237\u767b\u5f55",reset:"\u7528\u6237\u4fe1\u606f\u627e\u56de",register:"\u7528\u6237\u6ce8\u518c",
article:"\u7684\u6587\u7ae0",fans:"\u7684\u7c89\u4e1d",followed:"\u5df2\u5173\u6ce8 ",unfollowed:"\u5df2\u53d6\u6d88\u5173\u6ce8 ",email:"\u9a8c\u8bc1\u90ae\u4ef6\u5df2\u53d1\u9001\u5230\u65b0\u90ae\u7bb1\uff0c\u901a\u8fc7\u9a8c\u8bc1\u540e\u624d\u4fdd\u5b58\u4fee\u6539",updated:"\u7528\u6237\u4fe1\u606f\u66f4\u65b0\u6210\u529f",noUpdate:"\u7528\u6237\u4fe1\u606f\u6682\u65e0\u53d8\u66f4",noLogin:"\u60a8\u8fd8\u672a\u767b\u5f55"},TAG:{title:"\u70ed\u95e8\u6807\u7b7e",removed:"\u6210\u529f\u5220\u9664 ",
updated:"\u6210\u529f\u66f4\u65b0 ",noUpdate:"\u6807\u7b7e\u6682\u65e0\u53d8\u66f4"},FILTER:{role:"\u7981\u8a00 \u5f85\u9a8c\u8bc1 \u4f1a\u5458 \u7ec4\u5458 \u7f16\u8f91 \u7ba1\u7406\u5458".split(" "),follow:["\u5173\u6ce8","\u5df2\u5173\u6ce8"],favor:["\u652f\u6301","\u5df2\u652f\u6301"],mark:["\u6536\u85cf","\u5df2\u6536\u85cf"],oppose:["\u53cd\u5bf9","\u5df2\u53cd\u5bf9"],highlight:["\u7f6e\u9876","\u53d6\u6d88\u7f6e\u9876"],turn:["\u5f00\u542f","\u5173\u95ed"],edit:["\u6dfb\u52a0","\u7f16\u8f91"],
gender:{male:"\u7537",female:"\u5973"}},DATETIME:{second:"\u79d2",minute:"\u5206",hour:"\u65f6",day:"\u5929",month:"\u6708",year:"\u5e74",full:"yyyy\u5e74MM\u6708dd\u65e5 HH:mm","short":"MM-dd HH:mm",dayAgo:"\u5929\u524d",hourAgo:"\u5c0f\u65f6\u524d",minuteAgo:"\u5206\u949f\u524d",secondAgo:"\u521a\u521a"}})}]);"use strict";
angular.module("jsGen","jsGen.tools jsGen.router jsGen.filters jsGen.services jsGen.locale jsGen.directives jsGen.controllers".split(" ")).config(["$httpProvider","app",function(a,b){var c=0,d=!1,f={count:0,total:0,cancel:function(){c=0;d=!1;this.total=this.count=0;b.loading(!1,this)}};a.defaults.transformRequest.push(function(a){c+=1;f.count=c;f.total+=1;d||window.setTimeout(function(){!d&&0<c&&(d=!0,b.loading(!0,f))},1E3);return a});a.defaults.transformResponse.push(function(a){c-=1;f.count=c;d&&
0===c&&f.cancel();return a});a.interceptors.push(function(){return{response:function(a){var c,d=a.data;angular.isObject(d)&&(b.timestamp=d.timestamp,c=!d.ack&&d.error);return c?(b.toast.error(c.message,c.name),b.q.reject(d)):a},responseError:function(a){var c=a.data||a;a=a.status||"";var d=c.message||(angular.isObject(c)?"Error!":c);b.toast.error(d,a);return b.q.reject(c)}}})}]).run(["app","$q","$rootScope","$http","$location","$timeout","$filter","$locale","getFile","tools","toast","timing","cache",
"restAPI","sanitize","mdParse","mdEditor","CryptoJS","promiseGet","myConf","anchorScroll","applyFn","param",function(a,b,c,d,f,e,g,h,k,m,l,p,n,t,r,u,x,v,s,C,D,z,E){function B(){var a=q.viewWidth=$(window).width();q.isPocket=480>a;q.isPhone=768>a;q.isTablet=!q.isPhone&&980>a;q.isDesktop=980<=a}function A(){t.index.get({},function(b){a.timeOffset=Date.now()-b.timestamp;b=b.data;b.title2=b.description;b.info.angularjs=angular.version.full;a.union(q,b);a.checkUser()})}var w=!1,y="",q=c.global={isAdmin:!1,
isEditor:!1,isLogin:!1};window.app=a;a.q=b;a.http=d;a.toast=l;a.param=E;a.timing=p;a.location=f;a.timeout=e;a.timeOffset=0;a.timestamp=Date.now()+0;a.filter=g;a.locale=h;a.anchorScroll=D;a.getFile=k;a.cache=n;a.restAPI=t;a.sanitize=r;a.mdParse=u;a.mdEditor=x;a.CryptoJS=v;a.promiseGet=s;a.myConf=C;a.rootScope=c;angular.extend(a,m);a.loading=function(a,b){c.loading.show=a;z()};a.validate=function(b,c){var d=[],e=[];b.$broadcast("genTooltipValidate",d,c);a.each(d,function(a){a.validate&&a.$invalid&&
e.push(a)});0===e.length?(a.validate.errorList=null,b.$broadcast("genTooltipValidate",d,!0)):a.validate.errorList=e;return!a.validate.errorList};a.checkDirty=function(b,c,d){(b=a.union(b))&&c&&d?(a.intersect(b,d),a.each(b,function(a,b,d){angular.equals(a,c[b])&&delete d[b]}),b=a.digestArray(b),w=!a.isEmpty(b)):w=!1;return w?b:null};a.removeItem=function(b,c,d){return a.some(d,function(a,e){if(a[c]===b[c])return d.splice(e,1),!0})};a.checkUser=function(){q.isLogin=!!q.user;q.isAdmin=q.user&&5===q.user.role;
q.isEditor=q.user&&4<=q.user.role};a.clearUser=function(){q.user=null;a.checkUser()};a.checkFollow=function(b){var c=q.user||{};b.isMe=b._id===c._id;b.isFollow=!b.isMe&&a.some(c.followList,function(a){return a===b._id})};c.loading={show:!1};c.validateTooltip={validate:!0,validateMsg:h.VALIDATE};c.unSaveModal={confirmBtn:h.BTN_TEXT.confirm,confirmFn:function(){c.$emit("loadNext");return!0},cancelBtn:h.BTN_TEXT.cancel,cancelFn:!0};c.$on("$locationChangeStart",function(a,b,d){w?(a.preventDefault(),y=
b,c.unSaveModal.modal(!0)):y=""});c.$on("loadNext",function(a){a.preventDefault();w&&y&&(w=!1,window.location.href=y)});c.goBack=function(){window.history.go(-1)};c.logout=function(){t.user.get({ID:"logout"},function(){q.user=null;a.checkUser();f.path("/")})};c.followMe=function(b){t.user.save({ID:b._id},{follow:!b.isFollow},function(c){c.follow?(q.user.followList.push(b._id),a.toast.success(h.USER.followed+b.name,h.RESPONSE.success)):a.some(q.user.followList,function(c,d,e){if(c===b._id)return e.splice(d,
1),a.toast.success(h.USER.unfollowed+b.name,h.RESPONSE.success),!0});b.fans+=b.isFollow?-1:1;b.isFollow=!b.isFollow})};$(window).resize(z.bind(null,B));B();t.index.get({},function(b){a.timeOffset=Date.now()-b.timestamp;b=b.data;b.title2=b.description;b.info.angularjs=angular.version.full;a.union(q,b);a.checkUser()});p(function(){24E4<=Date.now()-a.timestamp-a.timeOffset&&A()},6E4);A()}]);