(function(c){c(["jquery"],function(c){return function(){function u(a){function r(){if(!(0<c(":focus",k).length))return k.fadeOut(e.fadeOut,function(){n(k);e.onFadeOut&&e.onFadeOut();z.state="hidden";z.endTime=new Date;p&&p(z)})}var e=d(),h=a.iconClass||e.iconClass;"undefined"!=typeof a.optionsOverride&&(e=c.extend(e,a.optionsOverride),h=a.optionsOverride.iconClass||h);m++;g=f(e);var t=null,k=c("<div/>"),v=c("<div/>"),u=c("<div/>"),z={toastId:m,state:"visible",startTime:new Date,options:e,map:a};a.iconClass&&
k.addClass(e.toastClass).addClass(h);a.title&&(v.append(a.title).addClass(e.titleClass),k.append(v));a.message&&(u.append(a.message).addClass(e.messageClass),k.append(u));k.hide();e.newestOnTop?g.prepend(k):g.append(k);k.fadeIn(e.fadeIn,e.onFadeIn);0<e.timeOut&&(t=setTimeout(r,e.timeOut));k.hover(function(){clearTimeout(t);k.stop(!0,!0).fadeIn(e.fadeIn)},function(){(0<e.timeOut||0<e.extendedTimeOut)&&(t=setTimeout(r,e.extendedTimeOut))});!e.onclick&&e.tapToDismiss&&k.click(r);e.onclick&&k.click(function(){e.onclick()&&
r()});p&&p(z);return e.debug&&console&&console.log(z),k}function f(a){return(a||(a=d()),g=c("#"+a.containerId),g.length)?g:(g=c("<div/>").attr("id",a.containerId).addClass(a.positionClass),g.appendTo(c(a.target)),g)}function d(){return c.extend({},t,a.options)}function n(a){(g||(g=f()),a.is(":visible"))||(a.remove(),0===g.children().length&&g.remove())}var g,p,m=0,t={tapToDismiss:!0,toastClass:"toast",containerId:"toast-container",debug:!1,fadeIn:300,onFadeIn:void 0,fadeOut:1E3,onFadeOut:void 0,extendedTimeOut:1E3,
iconClasses:{error:"toast-error",info:"toast-info",success:"toast-success",warning:"toast-warning"},iconClass:"toast-info",positionClass:"toast-top-right",timeOut:5E3,titleClass:"toast-title",messageClass:"toast-message",target:"body",newestOnTop:!0},a={clear:function(a){var p=d();(g||f(p),a&&0===c(":focus",a).length)?a.fadeOut(p.fadeOut,function(){n(a)}):g.children().length&&g.fadeOut(p.fadeOut,function(){g.remove()})},error:function(a,c,e){return u({type:"error",iconClass:d().iconClasses.error,
message:a,optionsOverride:e,title:c})},getContainer:f,info:function(a,c,e){return u({type:"info",iconClass:d().iconClasses.info,message:a,optionsOverride:e,title:c})},options:{},subscribe:function(a){p=a},success:function(a,c,e){return u({type:"success",iconClass:d().iconClasses.success,message:a,optionsOverride:e,title:c})},version:"1.3.1",warning:function(a,c,e){return u({type:"warning",iconClass:d().iconClasses.warning,message:a,optionsOverride:e,title:c})}};return a}()})})("function"==typeof define&&
define.amd?define:function(c,l){"undefined"!=typeof module&&module.exports?module.exports=l(require(c[0])):window.toastr=l(window.jQuery)});var q=null;window.PR_SHOULD_USE_CONTINUATION=!0;
(function(){function c(a){function e(b){var a=b.charCodeAt(0);if(92!==a)return a;var k=b.charAt(1);return(a=v[k])?a:"0"<=k&&"7">=k?parseInt(b.substring(1),8):"u"===k||"x"===k?parseInt(b.substring(2),16):b.charCodeAt(1)}function b(b){if(32>b)return(16>b?"\\x0":"\\x")+b.toString(16);b=String.fromCharCode(b);if("\\"===b||"-"===b||"["===b||"]"===b)b="\\"+b;return b}function k(a){var w=a.substring(1,a.length-1).match(/\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\S\s]|[^\\]/g);a=
[];for(var d=[],J="^"===w[0],x=J?1:0,h=w.length;x<h;++x){var c=w[x];if(/\\[bdsw]/i.test(c))a.push(c);else{var c=e(c),D;x+2<h&&"-"===w[x+1]?(D=e(w[x+2]),x+=2):D=c;d.push([c,D]);65>D||122<c||(65>D||90<c||d.push([Math.max(65,c)|32,Math.min(D,90)|32]),97>D||122<c||d.push([Math.max(97,c)&-33,Math.min(D,122)&-33]))}}d.sort(function(b,a){return b[0]-a[0]||a[1]-b[1]});w=[];c=[NaN,NaN];for(x=0;x<d.length;++x)h=d[x],h[0]<=c[1]+1?c[1]=Math.max(c[1],h[1]):w.push(c=h);d=["["];J&&d.push("^");d.push.apply(d,a);
for(x=0;x<w.length;++x)h=w[x],d.push(b(h[0])),h[1]>h[0]&&(h[1]+1>h[0]&&d.push("-"),d.push(b(h[1])));d.push("]");return d.join("")}function w(b){for(var a=b.source.match(/\[(?:[^\\\]]|\\[\S\s])*]|\\u[\dA-Fa-f]{4}|\\x[\dA-Fa-f]{2}|\\\d+|\\[^\dux]|\(\?[!:=]|[()^]|[^()[\\^]+/g),e=a.length,w=[],c=0,f=0;c<e;++c){var g=a[c];"("===g?++f:"\\"===g.charAt(0)&&(g=+g.substring(1))&&g<=f&&(w[g]=-1)}for(c=1;c<w.length;++c)-1===w[c]&&(w[c]=++d);for(f=c=0;c<e;++c)g=a[c],"("===g?(++f,void 0===w[f]&&(a[c]="(?:")):"\\"===
g.charAt(0)&&(g=+g.substring(1))&&g<=f&&(a[c]="\\"+w[f]);for(f=c=0;c<e;++c)"^"===a[c]&&"^"!==a[c+1]&&(a[c]="");if(b.ignoreCase&&h)for(c=0;c<e;++c)g=a[c],b=g.charAt(0),2<=g.length&&"["===b?a[c]=k(g):"\\"!==b&&(a[c]=g.replace(/[A-Za-z]/g,function(b){b=b.charCodeAt(0);return"["+String.fromCharCode(b&-33,b|32)+"]"}));return a.join("")}for(var d=0,h=!1,c=!1,f=0,g=a.length;f<g;++f){var p=a[f];if(p.ignoreCase)c=!0;else if(/[a-z]/i.test(p.source.replace(/\\u[\da-f]{4}|\\x[\da-f]{2}|\\[^UXux]/gi,""))){h=!0;
c=!1;break}}for(var v={b:8,t:9,n:10,v:11,f:12,r:13},s=[],f=0,g=a.length;f<g;++f){p=a[f];if(p.global||p.multiline)throw Error(""+p);s.push("(?:"+w(p)+")")}return RegExp(s.join("|"),c?"gi":"g")}function l(a){function e(a){switch(a.nodeType){case 1:if(b.test(a.className))break;for(var h=a.firstChild;h;h=h.nextSibling)e(h);h=a.nodeName;if("BR"===h||"LI"===h)c[k]="\n",d[k<<1]=w++,d[k++<<1|1]=a;break;case 3:case 4:h=a.nodeValue,h.length&&(h=g?h.replace(/\r\n?/g,"\n"):h.replace(/[\t\n\r ]+/g," "),c[k]=h,
d[k<<1]=w,w+=h.length,d[k++<<1|1]=a)}}var b=/(?:^|\s)nocode(?:\s|$)/,c=[],w=0,d=[],k=0,h;a.currentStyle?h=a.currentStyle.whiteSpace:window.getComputedStyle&&(h=document.defaultView.getComputedStyle(a,q).getPropertyValue("white-space"));var g=h&&"pre"===h.substring(0,3);e(a);return{a:c.join("").replace(/\n$/,""),c:d}}function u(a,e,b,c){e&&(a={a:e,d:a},b(a),c.push.apply(c,a.e))}function f(a,e){function b(a){for(var c=a.d,g=[c,"pln"],f=0,v=a.a.match(d)||[],s={},l=0,n=v.length;l<n;++l){var m=v[l],t=
s[m],C=void 0,A;if("string"===typeof t)A=!1;else{var r=k[m.charAt(0)];if(r)C=m.match(r[1]),t=r[0];else{for(A=0;A<h;++A)if(r=e[A],C=m.match(r[1])){t=r[0];break}C||(t="pln")}!(A=5<=t.length&&"lang-"===t.substring(0,5))||C&&"string"===typeof C[1]||(A=!1,t="src");A||(s[m]=t)}r=f;f+=m.length;if(A){A=C[1];var y=m.indexOf(A),G=y+A.length;C[2]&&(G=m.length-C[2].length,y=G-A.length);t=t.substring(5);u(c+r,m.substring(0,y),b,g);u(c+r+y,A,p(t,A),g);u(c+r+G,m.substring(G),b,g)}else g.push(c+r,t)}a.e=g}var k=
{},d;(function(){for(var b=a.concat(e),h=[],x={},g=0,f=b.length;g<f;++g){var p=b[g],m=p[3];if(m)for(var v=m.length;0<=--v;)k[m.charAt(v)]=p;p=p[1];m=""+p;x.hasOwnProperty(m)||(h.push(p),x[m]=q)}h.push(/[\S\s]/);d=c(h)})();var h=e.length;return b}function d(a){var e=[],b=[];a.tripleQuotedStrings?e.push(["str",/^(?:'''(?:[^'\\]|\\[\S\s]|''?(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\S\s]|""?(?=[^"]))*(?:"""|$)|'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$))/,q,"'\""]):a.multiLineStrings?e.push(["str",
/^(?:'(?:[^'\\]|\\[\S\s])*(?:'|$)|"(?:[^"\\]|\\[\S\s])*(?:"|$)|`(?:[^\\`]|\\[\S\s])*(?:`|$))/,q,"'\"`"]):e.push(["str",/^(?:'(?:[^\n\r'\\]|\\.)*(?:'|$)|"(?:[^\n\r"\\]|\\.)*(?:"|$))/,q,"\"'"]);a.verbatimStrings&&b.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,q]);var c=a.hashComments;c&&(a.cStyleComments?(1<c?e.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,q,"#"]):e.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\n\r]*)/,q,"#"]),b.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,
q])):e.push(["com",/^#[^\n\r]*/,q,"#"]));a.cStyleComments&&(b.push(["com",/^\/\/[^\n\r]*/,q]),b.push(["com",/^\/\*[\S\s]*?(?:\*\/|$)/,q]));a.regexLiterals&&b.push(["lang-regex",/^(?:^^\.?|[!+-]|!=|!==|#|%|%=|&|&&|&&=|&=|\(|\*|\*=|\+=|,|-=|->|\/|\/=|:|::|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|[?@[^]|\^=|\^\^|\^\^=|{|\||\|=|\|\||\|\|=|~|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\s*(\/(?=[^*/])(?:[^/[\\]|\\[\S\s]|\[(?:[^\\\]]|\\[\S\s])*(?:]|$))+\/)/]);(c=a.types)&&
b.push(["typ",c]);a=(""+a.keywords).replace(/^ | $/g,"");a.length&&b.push(["kwd",RegExp("^(?:"+a.replace(/[\s,]+/g,"|")+")\\b"),q]);e.push(["pln",/^\s+/,q," \r\n\t\u00a0"]);b.push(["lit",/^@[$_a-z][\w$@]*/i,q],["typ",/^(?:[@_]?[A-Z]+[a-z][\w$@]*|\w+_t\b)/,q],["pln",/^[$_a-z][\w$@]*/i,q],["lit",/^(?:0x[\da-f]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+-]?\d+)?)[a-z]*/i,q,"0123456789"],["pln",/^\\[\S\s]?/,q],["pun",/^.[^\s\w"-$'./@\\`]*/,q]);return f(e,b)}function n(a,e){function b(a){switch(a.nodeType){case 1:if(h.test(a.className))break;
if("BR"===a.nodeName)c(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)b(a);break;case 3:case 4:if(f){var e=a.nodeValue,g=e.match(k);if(g){var p=e.substring(0,g.index);a.nodeValue=p;(e=e.substring(g.index+g[0].length))&&a.parentNode.insertBefore(d.createTextNode(e),a.nextSibling);c(a);p||a.parentNode.removeChild(a)}}}}function c(b){function a(b,e){var c=e?b.cloneNode(!1):b,d=b.parentNode;if(d){var d=a(d,1),h=b.nextSibling;d.appendChild(c);for(var k=h;k;k=h)h=
k.nextSibling,d.appendChild(k)}return c}for(;!b.nextSibling;)if(b=b.parentNode,!b)return;b=a(b.nextSibling,0);for(var e;(e=b.parentNode)&&1===e.nodeType;)b=e;p.push(b)}var h=/(?:^|\s)nocode(?:\s|$)/,k=/\r\n?|\n/,d=a.ownerDocument,g;a.currentStyle?g=a.currentStyle.whiteSpace:window.getComputedStyle&&(g=d.defaultView.getComputedStyle(a,q).getPropertyValue("white-space"));var f=g&&"pre"===g.substring(0,3);for(g=d.createElement("LI");a.firstChild;)g.appendChild(a.firstChild);for(var p=[g],m=0;m<p.length;++m)b(p[m]);
e===(e|0)&&p[0].setAttribute("value",e);var v=d.createElement("OL");v.className="linenums";for(var s=Math.max(0,e-1|0)||0,m=0,l=p.length;m<l;++m)g=p[m],g.className="L"+(m+s)%10,g.firstChild||g.appendChild(d.createTextNode("\u00a0")),v.appendChild(g);a.appendChild(v)}function g(a,e){for(var b=e.length;0<=--b;){var c=e[b];z.hasOwnProperty(c)?window.console&&console.warn("cannot override language handler %s",c):z[c]=a}}function p(a,e){a&&z.hasOwnProperty(a)||(a=/^\s*</.test(e)?"default-markup":"default-code");
return z[a]}function m(a){var e=a.g;try{var b=l(a.h),c=b.a;a.a=c;a.c=b.c;a.d=0;p(e,c)(a);var d=/\bMSIE\b/.test(navigator.userAgent),e=/\n/g,k=a.a,h=k.length,b=0,g=a.c,f=g.length,c=0,m=a.e,v=m.length;a=0;m[v]=h;var s,n;for(n=s=0;n<v;)m[n]!==m[n+2]?(m[s++]=m[n++],m[s++]=m[n++]):n+=2;v=s;for(n=s=0;n<v;){for(var t=m[n],r=m[n+1],y=n+2;y+2<=v&&m[y+1]===r;)y+=2;m[s++]=t;m[s++]=r;n=y}for(m.length=s;c<f;){var C=g[c+2]||h,A=m[a+2]||h,y=Math.min(C,A),u=g[c+1],z;if(1!==u.nodeType&&(z=k.substring(b,y))){d&&(z=
z.replace(e,"\r"));u.nodeValue=z;var F=u.ownerDocument,H=F.createElement("SPAN");H.className=m[a+1];var K=u.parentNode;K.replaceChild(H,u);H.appendChild(u);b<C&&(g[c+1]=u=F.createTextNode(k.substring(y,C)),K.insertBefore(u,H.nextSibling))}b=y;b>=C&&(c+=2);b>=A&&(a+=2)}}catch(I){"console"in window&&console.log(I&&I.stack?I.stack:I)}}var t=["break,continue,do,else,for,if,return,while"],a=[[t,"auto,case,char,const,default,double,enum,extern,float,goto,int,long,register,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],
"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],s=[a,"alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,dynamic_cast,explicit,export,friend,inline,late_check,mutable,namespace,nullptr,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],r=[a,"abstract,boolean,byte,extends,final,finally,implements,import,instanceof,null,native,package,strictfp,super,synchronized,throws,transient"],
e=[r,"as,base,by,checked,decimal,delegate,descending,dynamic,event,fixed,foreach,from,group,implicit,in,interface,internal,into,is,lock,object,out,override,orderby,params,partial,readonly,ref,sbyte,sealed,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,var"],a=[a,"debugger,eval,export,function,get,null,set,undefined,var,with,Infinity,NaN"],h=[t,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],
y=[t,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"],t=[t,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"],k=/^(DIR|FILE|vector|(de|priority_)?queue|list|stack|(const_)?iterator|(multi)?(set|map)|bitset|u?(int|float)\d*)/,v=/\S/,F=d({keywords:[s,e,a,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END"+
h,y,t],hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),z={};g(F,["default-code"]);g(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^<\!--[\S\s]*?(?:--\>|$)/],["lang-",/^<\?([\S\s]+?)(?:\?>|$)/],["lang-",/^<%([\S\s]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\S\s]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\S\s]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\S\s]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));g(f([["pln",/^\s+/,q," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,q,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w-.:]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^\s"'>]*(?:[^\s"'/>]|\/(?=\s)))/],["pun",/^[/<->]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^\s"'>]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],["lang-css",
/^style\s*=\s*([^\s"'>]+)/i]]),["in.tag"]);g(f([],[["atv",/^[\S\s]+/]]),["uq.val"]);g(d({keywords:s,hashComments:!0,cStyleComments:!0,types:k}),"c cc cpp cxx cyc m".split(" "));g(d({keywords:"null,true,false"}),["json"]);g(d({keywords:e,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,types:k}),["cs"]);g(d({keywords:r,cStyleComments:!0}),["java"]);g(d({keywords:t,hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);g(d({keywords:h,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),
["cv","py"]);g(d({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);g(d({keywords:y,hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);g(d({keywords:a,cStyleComments:!0,regexLiterals:!0}),["js"]);g(d({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,true,try,unless,until,when,while,yes",
hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);g(f([],[["str",/^[\S\s]+/]]),["regex"]);window.prettyPrintOne=function(a,e,b){var c=document.createElement("PRE");c.innerHTML=a;b&&n(c,b);m({g:e,i:b,h:c});return c.innerHTML};window.prettyPrint=function(a){function e(){for(var b=window.PR_SHOULD_USE_CONTINUATION?g.now()+250:Infinity;f<c.length&&g.now()<b;f++){var d=c[f],k=d.className;if(0<=k.indexOf("prettyprint")){var k=k.match(s),h,w;if(w=
!k){w=d;for(var x=void 0,D=w.firstChild;D;D=D.nextSibling)var l=D.nodeType,x=1===l?x?w:D:3===l?v.test(D.nodeValue)?w:x:x;w=(h=x===w?void 0:x)&&"CODE"===h.tagName}w&&(k=h.className.match(s));k&&(k=k[1]);w=!1;for(x=d.parentNode;x;x=x.parentNode)if(("pre"===x.tagName||"code"===x.tagName||"xmp"===x.tagName)&&x.className&&0<=x.className.indexOf("prettyprint")){w=!0;break}w||((w=(w=d.className.match(/\blinenums\b(?::(\d+))?/))?w[1]&&w[1].length?+w[1]:!0:!1)&&n(d,w),p={g:k,h:d,i:w},m(p))}}f<c.length?setTimeout(e,
250):a&&a()}for(var b=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],c=[],d=0;d<b.length;++d)for(var k=0,h=b[d].length;k<h;++k)c.push(b[d][k]);var b=q,g=Date;g.now||(g={now:function(){return+new Date}});var f=0,p,s=/\blang(?:uage)?-([\w.]+)(?!\S)/;e()};window.PR={createSimpleLexer:f,registerLangHandler:g,sourceDecorator:d,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",
PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();
(function(c){function l(b){return b}function u(b){return!1}function f(){}function d(){}function n(b){this.buttonBar=k.getElementById("wmd-button-bar"+b);this.preview=k.getElementById("wmd-preview"+b);this.input=k.getElementById("wmd-input"+b)}function g(b,a){var d=this,k=[],h=0,g="none",f,m,v,s=function(b,a){g!=b&&(g=b,a||l());z.isIE&&"moving"==g?v=null:m=setTimeout(n,1)},n=function(b){v=new p(a,b);m=void 0};this.setCommandMode=function(){g="command";l();m=setTimeout(n,0)};this.canUndo=function(){return 1<
h};this.canRedo=function(){return k[h+1]?!0:!1};this.undo=function(){d.canUndo()&&(f?(f.restore(),f=null):(k[h]=new p(a),k[--h].restore(),b&&b()));g="none";a.input.focus();n()};this.redo=function(){d.canRedo()&&(k[++h].restore(),b&&b());g="none";a.input.focus();n()};var l=function(){var e=v||new p(a);if(!e)return!1;"moving"==g?f||(f=e):(f&&(k[h-1].text!=f.text&&(k[h++]=f),f=null),k[h++]=e,k[h+1]=null,b&&b())},t=function(b){var a=!1;if((b.ctrlKey||b.metaKey)&&!b.altKey)switch(String.fromCharCode(b.charCode||
b.keyCode).toLowerCase()){case "y":d.redo();a=!0;break;case "z":b.shiftKey?d.redo():d.undo(),a=!0}a&&(b.preventDefault&&b.preventDefault(),c.event&&(c.event.returnValue=!1))},r=function(b){b.ctrlKey||b.metaKey||(b=b.keyCode,33<=b&&40>=b||63232<=b&&63235>=b?s("moving"):8==b||46==b||127==b?s("deleting"):13==b?s("newlines"):27==b?s("escape"):(16>b||20<b)&&91!=b&&s("typing"))};(function(){e.addEvent(a.input,"keypress",function(b){!b.ctrlKey&&!b.metaKey||(b.altKey||89!=b.keyCode&&90!=b.keyCode)||b.preventDefault()});
var b=function(){(z.isIE||v&&v.text!=a.input.value)&&void 0==m&&(g="paste",l(),n())};e.addEvent(a.input,"keydown",t);e.addEvent(a.input,"keydown",r);e.addEvent(a.input,"mousedown",function(){s("moving")});a.input.onpaste=b;a.input.ondrop=b})();n(!0);l()}function p(b,a){var c=this,h=b.input;this.init=function(){e.isVisible(h)&&(a||!k.activeElement||k.activeElement===h)&&(this.setInputAreaSelectionStartEnd(),this.scrollTop=h.scrollTop,!this.text&&h.selectionStart||0===h.selectionStart)&&(this.text=
h.value)};this.setInputAreaSelection=function(){if(e.isVisible(h))if(void 0!==h.selectionStart&&!z.isOpera)h.focus(),h.selectionStart=c.start,h.selectionEnd=c.end,h.scrollTop=c.scrollTop;else if(k.selection&&(!k.activeElement||k.activeElement===h)){h.focus();var b=h.createTextRange();b.moveStart("character",-h.value.length);b.moveEnd("character",-h.value.length);b.moveEnd("character",c.end);b.moveStart("character",c.start);b.select()}};this.setInputAreaSelectionStartEnd=function(){if(!b.ieCachedRange&&
(h.selectionStart||0===h.selectionStart))c.start=h.selectionStart,c.end=h.selectionEnd;else if(k.selection){c.text=e.fixEolChars(h.value);var a=b.ieCachedRange||k.selection.createRange(),d=e.fixEolChars(a.text),g="\u0007"+d+"\u0007";a.text=g;var f=e.fixEolChars(h.value);a.moveStart("character",-g.length);a.text=d;c.start=f.indexOf("\u0007");c.end=f.lastIndexOf("\u0007")-1;if(g=c.text.length-e.fixEolChars(h.value).length){for(a.moveStart("character",-d.length);g--;)d+="\n",c.end+=1;a.text=d}b.ieCachedRange&&
(c.scrollTop=b.ieCachedScrollTop);b.ieCachedRange=null;this.setInputAreaSelection()}};this.restore=function(){void 0!=c.text&&c.text!=h.value&&(h.value=c.text);this.setInputAreaSelection();h.scrollTop=c.scrollTop};this.getChunks=function(){var b=new d;b.before=e.fixEolChars(c.text.substring(0,c.start));b.startTag="";b.selection=e.fixEolChars(c.text.substring(c.start,c.end));b.endTag="";b.after=e.fixEolChars(c.text.substring(c.end));b.scrollTop=c.scrollTop;return b};this.setChunks=function(b){b.before+=
b.startTag;b.after=b.endTag+b.after;this.start=b.before.length;this.end=b.before.length+b.selection.length;this.text=b.before+b.selection+b.after;this.scrollTop=b.scrollTop};this.init()}function m(b,a,d){var g,f,m,p=function(){var b=0;c.innerHeight?b=c.pageYOffset:k.documentElement&&k.documentElement.scrollTop?b=k.documentElement.scrollTop:k.body&&(b=k.body.scrollTop);return b},s=function(){if(a.preview&&"none"!==a.preview.style.display){var e=a.input.value;if(!e||e!=m){m=e;var c=(new Date).getTime(),
e=b.makeHtml(e);f=(new Date).getTime()-c;C(e)}}},v=function(){g&&(clearTimeout(g),g=void 0);var b=0,b=f;3E3<b&&(b=3E3);g=setTimeout(s,b)};this.refresh=function(b){b?(m="",s()):v()};this.processingTime=function(){return f};var n=!0,l=function(b){var e=a.preview,c=e.parentNode,h=e.nextSibling;c.removeChild(e);e.innerHTML=b;h?c.insertBefore(e,h):c.appendChild(e)},t=function(b){a.preview.innerHTML=b},r,y=function(b){if(r)return r(b);try{t(b),r=t}catch(a){r=l,r(b)}},C=function(b){var e=h.getTop(a.input)-
p();a.preview&&(y(b),d());a.preview&&(a.preview.scrollTop=(a.preview.scrollHeight-a.preview.clientHeight)*(a.preview.scrollHeight<=a.preview.clientHeight?1:a.preview.scrollTop/(a.preview.scrollHeight-a.preview.clientHeight)));if(n)n=!1;else{var k=h.getTop(a.input)-p();z.isIE?setTimeout(function(){c.scrollBy(0,k-e)},0):c.scrollBy(0,k-e)}};(function(b,a){e.addEvent(b,"input",a);b.onpaste=a;b.ondrop=a;e.addEvent(b,"keypress",a);e.addEvent(b,"keydown",a)})(a.input,v);s();a.preview&&(a.preview.scrollTop=
0)}function t(b,a,h,d,g,f,m){function s(b){t.focus();if(b.textOp){h&&h.setCommandMode();var e=new p(a);if(!e)return;var c=e.getChunks(),k=function(){t.focus();c&&e.setChunks(c);e.restore();d.refresh()};b.textOp(c,k)||k()}b.execute&&b.execute(h)}function v(b,e){var c=b.getElementsByTagName("span")[0];e?(c.style.backgroundPosition=b.XShift+" 0px",b.onmouseover=function(){c.style.backgroundPosition=this.XShift+" -40px"},b.onmouseout=function(){c.style.backgroundPosition=this.XShift+" 0px"},z.isIE&&(b.onmousedown=
function(){k.activeElement&&k.activeElement!==a.input||(a.ieCachedRange=document.selection.createRange(),a.ieCachedScrollTop=a.input.scrollTop)}),b.isHelp||(b.onclick=function(){if(this.onmouseout)this.onmouseout();s(this);return!1})):(c.style.backgroundPosition=b.XShift+" -20px",b.onmouseover=b.onmouseout=b.onclick=function(){})}function n(b){"string"===typeof b&&(b=g[b]);return function(){b.apply(g,arguments)}}function l(){h&&(v(r.undo,h.canUndo()),v(r.redo,h.canRedo()))}var t=a.input,r={};(function(){var e=
a.buttonBar,c=document.createElement("ul");c.id="wmd-button-row"+b;c.className="wmd-button-row";var c=e.appendChild(c),h=0,e=function(a,e,d,k){var g=document.createElement("li");g.className="wmd-button";g.style.left=h+"px";h+=25;var f=document.createElement("span");g.id=a+b;g.appendChild(f);g.title=e;g.XShift=d;k&&(g.textOp=k);v(g,!0);c.appendChild(g);return g},d=function(a){var e=document.createElement("li");e.className="wmd-spacer wmd-spacer"+a;e.id="wmd-spacer"+a+b;c.appendChild(e);h+=25};r.bold=
e("wmd-bold-button",m("bold"),"0px",n("doBold"));r.italic=e("wmd-italic-button",m("italic"),"-20px",n("doItalic"));d(1);r.link=e("wmd-link-button",m("link"),"-40px",n(function(b,a){return this.doLinkOrImage(b,a,!1)}));r.quote=e("wmd-quote-button",m("quote"),"-60px",n("doBlockquote"));r.code=e("wmd-code-button",m("code"),"-80px",n("doCode"));r.image=e("wmd-image-button",m("image"),"-100px",n(function(b,a){return this.doLinkOrImage(b,a,!0)}));d(2);r.olist=e("wmd-olist-button",m("olist"),"-120px",n(function(b,
a){this.doList(b,a,!0)}));r.ulist=e("wmd-ulist-button",m("ulist"),"-140px",n(function(b,a){this.doList(b,a,!1)}));r.heading=e("wmd-heading-button",m("heading"),"-160px",n("doHeading"));r.hr=e("wmd-hr-button",m("hr"),"-180px",n("doHorizontalRule"));d(3);r.undo=e("wmd-undo-button",m("undo"),"-200px",null);r.undo.execute=function(b){b&&b.undo()};d=/win/.test(F.platform.toLowerCase())?m("redo"):m("redomac");r.redo=e("wmd-redo-button",d,"-220px",null);r.redo.execute=function(b){b&&b.redo()};f&&(e=document.createElement("li"),
d=document.createElement("span"),e.appendChild(d),e.className="wmd-button wmd-help-button",e.id="wmd-help-button"+b,e.XShift="-240px",e.isHelp=!0,e.style.right="0px",e.title=m("help"),e.onclick=f.handler,v(e,!0),c.appendChild(e),r.help=e);l()})();var y="keydown";z.isOpera&&(y="keypress");e.addEvent(t,y,function(b){if((b.ctrlKey||b.metaKey)&&!b.altKey&&!b.shiftKey){switch(String.fromCharCode(b.charCode||b.keyCode).toLowerCase()){case "b":s(r.bold);break;case "i":s(r.italic);break;case "l":s(r.link);
break;case "q":s(r.quote);break;case "k":s(r.code);break;case "g":s(r.image);break;case "o":s(r.olist);break;case "u":s(r.ulist);break;case "h":s(r.heading);break;case "r":s(r.hr);break;case "y":s(r.redo);break;case "z":b.shiftKey?s(r.redo):s(r.undo);break;default:return}b.preventDefault&&b.preventDefault();c.event&&(c.event.returnValue=!1)}});e.addEvent(t,"keyup",function(b){!b.shiftKey||(b.ctrlKey||b.metaKey)||13!==(b.charCode||b.keyCode)||(b={},b.textOp=n("doAutoindent"),s(b))});z.isIE&&e.addEvent(t,
"keydown",function(b){if(27===b.keyCode)return!1});this.setUndoRedoButtonStates=l}function a(b,a){this.hooks=b;this.getString=a}function s(b){return b.replace(/^\s*(.*?)(?:\s+"(.+)")?\s*$/,function(b,a,e){a=a.replace(/\?.*$/,function(b){return b.replace(/\+/g," ")});a=decodeURIComponent(a);a=encodeURI(a).replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29");a=a.replace(/\?.*$/,function(b){return b.replace(/\+/g,"%2b")});e&&(e=e.trim?e.trim():e.replace(/^\s*/,"").replace(/\s*$/,""),e=e.replace(/"/g,
"quot;").replace(/\(/g,"&#40;").replace(/\)/g,"&#41;").replace(/</g,"&lt;").replace(/>/g,"&gt;"));return e?a+' "'+e+'"':a})}var r={};f.prototype={chain:function(b,a){var e=this[b];if(!e)throw Error("unknown hook "+b);this[b]=e===l?a:function(b){var c=Array.prototype.slice.call(arguments,0);c[0]=e.apply(null,c);return a.apply(null,c)}},set:function(b,a){if(!this[b])throw Error("unknown hook "+b);this[b]=a},addNoop:function(b){this[b]=l},addFalse:function(b){this[b]=u}};r.HookCollection=f;var e={},
h={},y={},k=c.document,v=c.RegExp,F=c.navigator,z={isIE:/msie/.test(F.userAgent.toLowerCase()),isIE_5or6:/msie 6/.test(F.userAgent.toLowerCase())||/msie 5/.test(F.userAgent.toLowerCase()),isOpera:/opera/.test(F.userAgent.toLowerCase())},G={bold:"Strong <strong> Ctrl+B",boldexample:"strong text",italic:"Emphasis <em> Ctrl+I",italicexample:"emphasized text",link:"Hyperlink <a> Ctrl+L",linkdescription:"enter link description here",linkdialog:'<p><b>Insert Hyperlink</b></p><p>http://example.com/ "optional title"</p>',
quote:"Blockquote <blockquote> Ctrl+Q",quoteexample:"Blockquote",code:"Code Sample <pre><code> Ctrl+K",codeexample:"enter code here",image:"Image <img> Ctrl+G",imagedescription:"enter image description here",imagedialog:"<p><b>Insert Image</b></p><p>http://example.com/images/diagram.jpg \"optional title\"<br><br>Need <a href='http://www.google.com/search?q=free+image+hosting' target='_blank'>free image hosting?</a></p>",olist:"Numbered List <ol> Ctrl+O",ulist:"Bulleted List <ul> Ctrl+U",litem:"List item",
heading:"Heading <h1>/<h2> Ctrl+H",headingexample:"Heading",hr:"Horizontal Rule <hr> Ctrl+R",undo:"Undo - Ctrl+Z",redo:"Redo - Ctrl+Y",redomac:"Redo - Ctrl+Shift+Z",help:"Markdown Editing Help"};r.Editor=function(b,e,c){c=c||{};"function"===typeof c.handler&&(c={helpButton:c});c.strings=c.strings||{};c.helpButton&&(c.strings.help=c.strings.help||c.helpButton.title);var h=function(b){return c.strings[b]||G[b]};e=e||"";var d=this.hooks=new r.HookCollection;d.addNoop("onPreviewRefresh");d.addNoop("postBlockquoteCreation");
d.addFalse("insertImageDialog");this.getConverter=function(){return b};var f=this,s;this.run=function(){if(!s){s=new n(e);var p=new a(d,h),v=new m(b,s,function(){d.onPreviewRefresh()}),r,l;/\?noundo/.test(k.location.href)||(r=new g(function(){v.refresh();l&&l.setUndoRedoButtonStates()},s),this.textOperation=function(b){r.setCommandMode();b();f.refreshPreview()});l=new t(e,s,r,v,p,c.helpButton,h);l.setUndoRedoButtonStates();(f.refreshPreview=function(){v.refresh(!0)})()}}};d.prototype.findTags=function(b,
a){var c=this,h;b&&(h=e.extendRegExp(b,"","$"),this.before=this.before.replace(h,function(b){c.startTag+=b;return""}),h=e.extendRegExp(b,"^",""),this.selection=this.selection.replace(h,function(b){c.startTag+=b;return""}));a&&(h=e.extendRegExp(a,"","$"),this.selection=this.selection.replace(h,function(b){c.endTag=b+c.endTag;return""}),h=e.extendRegExp(a,"^",""),this.after=this.after.replace(h,function(b){c.endTag=b+c.endTag;return""}))};d.prototype.trimWhitespace=function(b){var a,e=this;b?b=a="":
(b=function(b){e.before+=b;return""},a=function(b){e.after=b+e.after;return""});this.selection=this.selection.replace(/^(\s*)/,b).replace(/(\s*)$/,a)};d.prototype.skipLines=function(b,a,e){void 0===b&&(b=1);void 0===a&&(a=1);b++;a++;var c,h;navigator.userAgent.match(/Chrome/)&&"X".match(/()./);this.selection=this.selection.replace(/(^\n*)/,"");this.startTag+=v.$1;this.selection=this.selection.replace(/(\n*$)/,"");this.endTag+=v.$1;this.startTag=this.startTag.replace(/(^\n*)/,"");this.before+=v.$1;
this.endTag=this.endTag.replace(/(\n*$)/,"");this.after+=v.$1;if(this.before){for(c=h="";b--;)c+="\\n?",h+="\n";e&&(c="\\n*");this.before=this.before.replace(new v(c+"$",""),h)}if(this.after){for(c=h="";a--;)c+="\\n?",h+="\n";e&&(c="\\n*");this.after=this.after.replace(new v(c,""),h)}};e.isVisible=function(b){if(c.getComputedStyle)return"none"!==c.getComputedStyle(b,null).getPropertyValue("display");if(b.currentStyle)return"none"!==b.currentStyle.display};e.addEvent=function(b,a,e){b.attachEvent?
b.attachEvent("on"+a,e):b.addEventListener(a,e,!1)};e.removeEvent=function(b,a,e){b.detachEvent?b.detachEvent("on"+a,e):b.removeEventListener(a,e,!1)};e.fixEolChars=function(b){b=b.replace(/\r\n/g,"\n");return b=b.replace(/\r/g,"\n")};e.extendRegExp=function(b,a,e){if(null===a||void 0===a)a="";if(null===e||void 0===e)e="";b=b.toString();var c;b=b.replace(/\/([gim]*)$/,function(b,a){c=a;return""});b=b.replace(/(^\/|\/$)/g,"");return new v(a+b+e,c)};h.getTop=function(b,a){var e=b.offsetTop;if(!a)for(;b=
b.offsetParent;)e+=b.offsetTop;return e};h.getHeight=function(b){return b.offsetHeight||b.scrollHeight};h.getWidth=function(b){return b.offsetWidth||b.scrollWidth};h.getPageSize=function(){var b,a,e,c;self.innerHeight&&self.scrollMaxY?(b=k.body.scrollWidth,a=self.innerHeight+self.scrollMaxY):k.body.scrollHeight>k.body.offsetHeight?(b=k.body.scrollWidth,a=k.body.scrollHeight):(b=k.body.offsetWidth,a=k.body.offsetHeight);self.innerHeight?(e=self.innerWidth,c=self.innerHeight):k.documentElement&&k.documentElement.clientHeight?
(e=k.documentElement.clientWidth,c=k.documentElement.clientHeight):k.body&&(e=k.body.clientWidth,c=k.body.clientHeight);b=Math.max(b,e);a=Math.max(a,c);return[b,a,e,c]};y.createBackground=function(){var b=k.createElement("div"),a=b.style;b.className="wmd-prompt-background";a.position="absolute";a.top="0";a.zIndex="1000";z.isIE?a.filter="alpha(opacity=50)":a.opacity="0.5";var e=h.getPageSize();a.height=e[1]+"px";z.isIE?(a.left=k.documentElement.scrollLeft,a.width=k.documentElement.clientWidth):(a.left=
"0",a.width="100%");k.body.appendChild(b);return b};y.prompt=function(b,a,c){var d,g;void 0===a&&(a="");var f=function(b){27===(b.charCode||b.keyCode)&&m(!0)},m=function(b){e.removeEvent(k.body,"keydown",f);var a=g.value;b?a=null:(a=a.replace(/^http:\/\/(https?|ftp):\/\//,"$1://"),/^(?:https?|ftp):\/\//.test(a)||(a="http://"+a));d.parentNode.removeChild(d);c(a);return!1},s=function(){d=k.createElement("div");d.className="wmd-prompt-dialog";d.style.padding="10px;";d.style.position="fixed";d.style.width=
"400px";d.style.zIndex="1001";var c=k.createElement("div");c.innerHTML=b;c.style.padding="5px";d.appendChild(c);var c=k.createElement("form"),s=c.style;c.onsubmit=function(){return m(!1)};s.padding="0";s.margin="0";s.cssFloat="left";s.width="100%";s.textAlign="center";s.position="relative";d.appendChild(c);g=k.createElement("input");g.type="text";g.value=a;s=g.style;s.display="block";s.width="80%";s.marginLeft=s.marginRight="auto";c.appendChild(g);var p=k.createElement("input");p.type="button";p.onclick=
function(){return m(!1)};p.value="OK";s=p.style;s.margin="10px";s.display="inline";s.width="7em";var v=k.createElement("input");v.type="button";v.onclick=function(){return m(!0)};v.value="Cancel";s=v.style;s.margin="10px";s.display="inline";s.width="7em";c.appendChild(p);c.appendChild(v);e.addEvent(k.body,"keydown",f);d.style.top="50%";d.style.left="50%";d.style.display="block";z.isIE_5or6&&(d.style.position="absolute",d.style.top=k.documentElement.scrollTop+200+"px",d.style.left="50%");k.body.appendChild(d);
d.style.marginTop=-(h.getHeight(d)/2)+"px";d.style.marginLeft=-(h.getWidth(d)/2)+"px"};setTimeout(function(){s();var b=a.length;if(void 0!==g.selectionStart)g.selectionStart=0,g.selectionEnd=b;else if(g.createTextRange){var e=g.createTextRange();e.collapse(!1);e.moveStart("character",-b);e.moveEnd("character",b);e.select()}g.focus()},0)};var B=a.prototype;B.prefixes="(?:\\s{4,}|\\s*>|\\s*-\\s+|\\s*\\d+\\.|=|\\+|-|_|\\*|#|\\s*\\[[^\n]]+\\]:)";B.unwrap=function(b){var a=new v("([^\\n])\\n(?!(\\n|"+
this.prefixes+"))","g");b.selection=b.selection.replace(a,"$1 $2")};B.wrap=function(b,a){this.unwrap(b);var e=new v("(.{1,"+a+"})( +|$\\n?)","gm"),c=this;b.selection=b.selection.replace(e,function(b,a){return(new v("^"+c.prefixes,"")).test(b)?b:a+"\n"});b.selection=b.selection.replace(/\s+$/,"")};B.doBold=function(b,a){return this.doBorI(b,a,2,this.getString("boldexample"))};B.doItalic=function(b,a){return this.doBorI(b,a,1,this.getString("italicexample"))};B.doBorI=function(b,a,e,c){b.trimWhitespace();
b.selection=b.selection.replace(/\n{2,}/g,"\n");var h=/(\**$)/.exec(b.before)[0];a=/(^\**)/.exec(b.after)[0];h=Math.min(h.length,a.length);h>=e&&(2!=h||1!=e)?(b.before=b.before.replace(v("[*]{"+e+"}$",""),""),b.after=b.after.replace(v("^[*]{"+e+"}",""),"")):!b.selection&&a?(b.after=b.after.replace(/^([*_]*)/,""),b.before=b.before.replace(/(\s?)$/,""),b.before=b.before+a+v.$1):(b.selection||a||(b.selection=c),e=1>=e?"*":"**",b.before+=e,b.after=e+b.after)};B.stripLinkDefs=function(b,a){return b=b.replace(/^[ ]{0,3}\[(\d+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?[ \t]*\n?[ \t]*(?:(\n*)["(](.+?)[")][ \t]*)?(?:\n+|$)/gm,
function(b,e,c,h,d){a[e]=b.replace(/\s*$/,"");return h?(a[e]=b.replace(/["(](.+?)[")]$/,""),h+d):""})};B.addLinkDef=function(b,a){var e=0,c={};b.before=this.stripLinkDefs(b.before,c);b.selection=this.stripLinkDefs(b.selection,c);b.after=this.stripLinkDefs(b.after,c);var h="",d=/(\[)((?:\[[^\]]*\]|[^\[\]])*)(\][ ]?(?:\n[ ]*)?\[)(\d+)(\])/g,k=function(b){e++;b=b.replace(/^[ ]{0,3}\[(\d+)\]:/,"  ["+e+"]:");h+="\n"+b},g=function(b,a,h,f,s,m){h=h.replace(d,g);return c[s]?(k(c[s]),a+h+f+e+m):b};b.before=
b.before.replace(d,g);a?k(a):b.selection=b.selection.replace(d,g);var f=e;b.after=b.after.replace(d,g);b.after&&(b.after=b.after.replace(/\n*$/,""));b.after||(b.selection=b.selection.replace(/\n*$/,""));b.after+="\n\n"+h;return f};B.doLinkOrImage=function(b,a,e){b.trimWhitespace();b.findTags(/\s*!?\[/,/\][ ]?(?:\n[ ]*)?(\[.*?\])?/);var c;if(1<b.endTag.length&&0<b.startTag.length)b.startTag=b.startTag.replace(/!?\[/,""),b.endTag="",this.addLinkDef(b,null);else if(b.selection=b.startTag+b.selection+
b.endTag,b.startTag=b.endTag="",/\n\n/.test(b.selection))this.addLinkDef(b,null);else{var h=this,d=function(d){c.parentNode.removeChild(c);null!==d&&(b.selection=(" "+b.selection).replace(/([^\\](?:\\\\)*)(?=[[\]])/g,"$1\\").substr(1),d=" [999]: "+s(d),d=h.addLinkDef(b,d),b.startTag=e?"![":"[",b.endTag="]["+d+"]",b.selection||(b.selection=e?h.getString("imagedescription"):h.getString("linkdescription")));a()};c=y.createBackground();e?this.hooks.insertImageDialog(d)||y.prompt(this.getString("imagedialog"),
"http://",d):y.prompt(this.getString("linkdialog"),"http://",d);return!0}};B.doAutoindent=function(b,a){var e=!1;b.before=b.before.replace(/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]*\n$/,"\n\n");b.before=b.before.replace(/(\n|^)[ ]{0,3}>[ \t]*\n$/,"\n\n");b.before=b.before.replace(/(\n|^)[ \t]+\n$/,"\n\n");b.selection||/^[ \t]*(?:\n|$)/.test(b.after)||(b.after=b.after.replace(/^[^\n]*/,function(a){b.selection=a;return""}),e=!0);/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]+.*\n$/.test(b.before)&&this.doList&&this.doList(b);
/(\n|^)[ ]{0,3}>[ \t]+.*\n$/.test(b.before)&&this.doBlockquote&&this.doBlockquote(b);/(\n|^)(\t|[ ]{4,}).*\n$/.test(b.before)&&this.doCode&&this.doCode(b);e&&(b.after=b.selection+b.after,b.selection="")};B.doBlockquote=function(b,a){b.selection=b.selection.replace(/^(\n*)([^\r]+?)(\n*)$/,function(a,e,c,h){b.before+=e;b.after=h+b.after;return c});b.before=b.before.replace(/(>[ \t]*)$/,function(a,e){b.selection=e+b.selection;return""});b.selection=b.selection.replace(/^(\s|>)+$/,"");b.selection=b.selection||
this.getString("quoteexample");var e="",c="",h;if(b.before){for(var d=b.before.replace(/\n$/,"").split("\n"),k=!1,g=0;g<d.length;g++){var f=!1;h=d[g];k=k&&0<h.length;/^>/.test(h)?(f=!0,!k&&1<h.length&&(k=!0)):f=/^[ \t]*$/.test(h)?!0:k;f?e+=h+"\n":(c+=e+h,e="\n")}/(^|\n)>/.test(e)||(c+=e,e="")}b.startTag=e;b.before=c;b.after&&(b.after=b.after.replace(/^\n?/,"\n"));b.after=b.after.replace(/^(((\n|^)(\n[ \t]*)*>(.+\n)*.*)+(\n[ \t]*)*)/,function(a){b.endTag=a;return""});e=function(a){var e=a?"> ":"";
b.startTag&&(b.startTag=b.startTag.replace(/\n((>|\s)*)\n$/,function(b,a){return"\n"+a.replace(/^[ ]{0,3}>?[ \t]*$/gm,e)+"\n"}));b.endTag&&(b.endTag=b.endTag.replace(/^\n((>|\s)*)\n/,function(b,a){return"\n"+a.replace(/^[ ]{0,3}>?[ \t]*$/gm,e)+"\n"}))};/^(?![ ]{0,3}>)/m.test(b.selection)?(this.wrap(b,70),b.selection=b.selection.replace(/^/gm,"> "),e(!0),b.skipLines()):(b.selection=b.selection.replace(/^[ ]{0,3}> ?/gm,""),this.unwrap(b),e(!1),!/^(\n|^)[ ]{0,3}>/.test(b.selection)&&b.startTag&&(b.startTag=
b.startTag.replace(/\n{0,2}$/,"\n\n")),!/(\n|^)[ ]{0,3}>.*$/.test(b.selection)&&b.endTag&&(b.endTag=b.endTag.replace(/^\n{0,2}/,"\n\n")));b.selection=this.hooks.postBlockquoteCreation(b.selection);/\n/.test(b.selection)||(b.selection=b.selection.replace(/^(> *)/,function(a,e){b.startTag+=e;return""}))};B.doCode=function(b,a){var e=/\S[ ]*$/.test(b.before);if(!/^[ ]*\S/.test(b.after)&&!e||/\n/.test(b.selection)){b.before=b.before.replace(/[ ]{4}$/,function(a){b.selection=a+b.selection;return""});var c=
e=1;/(\n|^)(\t|[ ]{4,}).*\n$/.test(b.before)&&(e=0);/^\n(\t|[ ]{4,})/.test(b.after)&&(c=0);b.skipLines(e,c);b.selection?/^[ ]{0,3}\S/m.test(b.selection)?/\n/.test(b.selection)?b.selection=b.selection.replace(/^/gm,"    "):b.before+="    ":b.selection=b.selection.replace(/^(?:[ ]{4}|[ ]{0,3}\t)/gm,""):(b.startTag="    ",b.selection=this.getString("codeexample"))}else b.trimWhitespace(),b.findTags(/`/,/`/),b.startTag||b.endTag?b.endTag&&!b.startTag?(b.before+=b.endTag,b.endTag=""):b.startTag=b.endTag=
"":(b.startTag=b.endTag="`",b.selection||(b.selection=this.getString("codeexample")))};B.doList=function(b,a,e){a=/^\n*(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*/;var c="-",h=1,d=function(){var b;e?(b=" "+h+". ",h++):b=" "+c+" ";return b},k=function(b){void 0===e&&(e=/^\s*\d/.test(b));return b=b.replace(/^[ ]{0,3}([*+-]|\d+[.])\s/gm,function(b){return d()})};b.findTags(/(\n|^)*[ ]{0,3}([*+-]|\d+[.])\s+/,null);!b.before||(/\n$/.test(b.before)||/^\n/.test(b.startTag))||
(b.before+=b.startTag,b.startTag="");if(b.startTag){var g=/\d+[.]/.test(b.startTag);b.startTag="";b.selection=b.selection.replace(/\n[ ]{4}/g,"\n");this.unwrap(b);b.skipLines();g&&(b.after=b.after.replace(a,k));if(e==g)return}var f=1;b.before=b.before.replace(/(\n|^)(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*$/,function(b){/^\s*([*+-])/.test(b)&&(c=v.$1);f=/[^\n]\n\n[^\n]/.test(b)?1:0;return k(b)});b.selection||(b.selection=this.getString("litem"));
var g=d(),s=1;b.after=b.after.replace(a,function(b){s=/[^\n]\n\n[^\n]/.test(b)?1:0;return k(b)});b.trimWhitespace(!0);b.skipLines(f,s,!0);b.startTag=g;a=g.replace(/./g," ");this.wrap(b,72-a.length);b.selection=b.selection.replace(/\n/g,"\n"+a)};B.doHeading=function(b,a){b.selection=b.selection.replace(/\s+/g," ");b.selection=b.selection.replace(/(^\s+|\s+$)/g,"");if(b.selection){var e=0;b.findTags(/#+[ ]*/,/[ ]*#+/);/#+/.test(b.startTag)&&(e=v.lastMatch.length);b.startTag=b.endTag="";b.findTags(null,
/\s?(-+|=+)/);/=+/.test(b.endTag)&&(e=1);/-+/.test(b.endTag)&&(e=2);b.startTag=b.endTag="";b.skipLines(1,1);e=0==e?2:e-1;if(0<e){var e=2<=e?"-":"=",c=b.selection.length;72<c&&(c=72);for(b.endTag="\n";c--;)b.endTag+=e}}else b.startTag="## ",b.selection=this.getString("headingexample"),b.endTag=" ##"};B.doHorizontalRule=function(b,a){b.startTag="----------\n";b.selection="";b.skipLines(2,1,!0)};c.Markdown=r})(window);
function Sanitize(c){var l;l=c||{};this.config={};this.config.elements=l.elements?l.elements:[];this.config.attributes=l.attributes?l.attributes:{};this.config.attributes[Sanitize.ALL]=this.config.attributes[Sanitize.ALL]?this.config.attributes[Sanitize.ALL]:[];this.config.allow_comments=l.allow_comments?l.allow_comments:!1;this.allowed_elements={};this.config.protocols=l.protocols?l.protocols:{};this.config.add_attributes=l.add_attributes?l.add_attributes:{};this.dom=l.dom?l.dom:document;for(c=0;c<
this.config.elements.length;c++)this.allowed_elements[this.config.elements[c]]=!0;this.config.remove_element_contents={};this.config.remove_all_contents=!1;if(l.remove_contents)if(l.remove_contents instanceof Array)for(c=0;c<l.remove_contents.length;c++)this.config.remove_element_contents[l.remove_contents[c]]=!0;else this.config.remove_all_contents=!0;this.transformers=l.transformers?l.transformers:[]}Sanitize.REGEX_PROTOCOL=/^([A-Za-z0-9\+\-\.\&\;\*\s]*?)(?:\:|&*0*58|&*x0*3a)/i;
Sanitize.RELATIVE="__relative__";
Sanitize.prototype.clean_node=function(c){function l(c,d){var f;for(f=0;f<d.length;f++)if(d[f]==c)return f;return-1}function u(){var c=[],d={},f,m;for(f=0;f<arguments.length;f++)if(arguments[f]&&arguments[f].length)for(m=0;m<arguments[f].length;m++)d[arguments[f][m]]||(d[arguments[f][m]]=!0,c.push(arguments[f][m]));return c}function f(c){var d;switch(c.nodeType){case 1:var p,m,t,a,s,r,e;p=[];m=c;a=!1;for(t=0;t<this.transformers.length;t++)if(s=this.transformers[t]({allowed_elements:this.allowed_elements,config:this.config,
node:c,node_name:c.nodeName.toLowerCase(),whitelist_nodes:this.whitelist_nodes,dom:this.dom}),null!=s)if("object"==typeof s){if(s.whitelist_nodes&&s.whitelist_nodes instanceof Array)for(a=0;a<s.whitelist_nodes.length;a++)-1==l(s.whitelist_nodes[a],this.whitelist_nodes)&&this.whitelist_nodes.push(s.whitelist_nodes[a]);a=s.whitelist?!0:!1;s.attr_whitelist&&(p=u(p,s.attr_whitelist));m=s.node?s.node:m}else throw Error("transformer output must be an object or null");c=m;t=c.nodeName.toLowerCase();m=this.current_element;
if(this.allowed_elements[t]||a){this.current_element=this.dom.createElement(c.nodeName);m.appendChild(this.current_element);a=this.config.attributes;a=u(a[t],a.__ALL__,p);for(p=0;p<a.length;p++)if(d=a[p],s=c.attributes[d])r=!0,this.config.protocols[t]&&this.config.protocols[t][d]&&(r=this.config.protocols[t][d],r=(e=s.nodeValue.toLowerCase().match(Sanitize.REGEX_PROTOCOL))?-1!=l(e[1],r):-1!=l(Sanitize.RELATIVE,r)),r&&(r=document.createAttribute(d),r.value=s.nodeValue,this.current_element.setAttributeNode(r));
if(this.config.add_attributes[t])for(d in this.config.add_attributes[t])r=document.createAttribute(d),r.value=this.config.add_attributes[t][d],this.current_element.setAttributeNode(r)}else if(-1!=l(c,this.whitelist_nodes)){for(this.current_element=c.cloneNode(!0);0<this.current_element.childNodes.length;)this.current_element.removeChild(this.current_element.firstChild);m.appendChild(this.current_element)}if(!this.config.remove_all_contents&&!this.config.remove_element_contents[t])for(p=0;p<c.childNodes.length;p++)f.call(this,
c.childNodes[p]);this.current_element.normalize&&this.current_element.normalize();this.current_element=m;break;case 3:d=c.cloneNode(!1);this.current_element.appendChild(d);break;case 5:d=c.cloneNode(!1);this.current_element.appendChild(d);break;case 8:this.config.allow_comments&&(d=c.cloneNode(!1),this.current_element.appendChild(d));break;default:console&&console.log&&console.log("unknown node type",c.nodeType)}}var d=this.dom.createDocumentFragment();this.current_element=d;this.whitelist_nodes=
[];for(i=0;i<c.childNodes.length;i++)f.call(this,c.childNodes[i]);d.normalize&&d.normalize();return d};Sanitize.Config||(Sanitize.Config={});
Sanitize.Config.BASIC={elements:"a b blockquote br cite code dd dl dt em i li ol p pre q small strike strong sub sup u ul".split(" "),attributes:{a:["href"],blockquote:["cite"],q:["cite"]},add_attributes:{a:{rel:"nofollow"}},protocols:{a:{href:["ftp","http","https","mailto",Sanitize.RELATIVE]},blockquote:{cite:["http","https",Sanitize.RELATIVE]},q:{cite:["http","https",Sanitize.RELATIVE]}}};
Sanitize.Config.RELAXED={elements:"a b blockquote br caption cite code col colgroup dd dl dt em h1 h2 h3 h4 h5 h6 i img li ol p pre q small strike strong sub sup table tbody td tfoot th thead tr u ul div".split(" "),attributes:{a:["href","title"],blockquote:["cite"],col:["span","width"],colgroup:["span","width"],img:"align alt height src title width".split(" "),ol:["start","type"],q:["cite"],table:["summary","width"],td:["abbr","axis","colspan","rowspan","width"],th:"abbr axis colspan rowspan scope width".split(" "),
ul:["type"],div:["class"]},protocols:{a:{href:["ftp","http","https","mailto",Sanitize.RELATIVE]},blockquote:{cite:["http","https",Sanitize.RELATIVE]},img:{src:["http","https",Sanitize.RELATIVE]},q:{cite:["http","https",Sanitize.RELATIVE]}}};Sanitize.Config.RESTRICTED={elements:["b","em","i","strong","u"]};
(function(){function c(a){this.tokens=[];this.tokens.links={};this.options=a||p.defaults;this.rules=m.normal;this.options.gfm&&(this.rules=this.options.tables?m.tables:m.gfm)}function l(a,c){this.options=c||p.defaults;this.links=a;this.rules=t.normal;if(!this.links)throw Error("Tokens array requires a `links` property.");this.options.gfm?this.rules=this.options.breaks?t.breaks:t.gfm:this.options.pedantic&&(this.rules=t.pedantic)}function u(a){this.tokens=[];this.token=null;this.options=a||p.defaults}
function f(a,c){return a.replace(c?/&/g:/&(?!#?\w+;)/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function d(a,c){a=a.source;c=c||"";return function e(d,g){if(!d)return RegExp(a,c);g=g.source||g;g=g.replace(/(^|[^\[])\^/g,"$1");a=a.replace(d,g);return e}}function n(){}function g(a){for(var c=1,d,e;c<arguments.length;c++)for(e in d=arguments[c],d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e]);return a}function p(a,d,m){if(m||"function"===
typeof d){m||(m=d,d=null);d&&(d=g({},p.defaults,d));var e=d.highlight,h,l,k=0;try{h=c.lex(a,d)}catch(v){return m(v)}l=h.length;var n=function(a){var c,b;!0!==a&&delete d.highlight;try{c=u.parse(h,d)}catch(k){b=k}d.highlight=e;return b?m(b):m(null,c)};if(!e||3>e.length)return n(!0);if(!l)return n();for(;k<h.length;k++)(function(a){return"code"!==a.type?--l||n():e(a.text,a.lang,function(e,b){if(null==b||b===a.text)return--l||n();a.text=b;a.escaped=!0;--l||n()})})(h[k])}else try{return d&&(d=g({},p.defaults,
d)),u.parse(c.lex(a,d),d)}catch(t){t.message+="\nPlease report this to https://github.com/chjj/marked.";if((d||p.defaults).silent)return"<p>An error occured:</p><pre>"+f(t.message+"",!0)+"</pre>";throw t;}}var m={newline:/^\n+/,code:/^( {4}[^\n]+\n*)+/,fences:n,hr:/^( *[-*_]){3,} *(?:\n+|$)/,heading:/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n+|$)/,nptable:n,lheading:/^([^\n]+)\n *(=|-){3,} *\n*/,blockquote:/^( *>[^\n]+(\n[^\n]+)*\n*)+/,list:/^( *)(bull) [\s\S]+?(?:hr|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,html:/^ *(?:comment|closed|closing) *(?:\n{2,}|\s*$)/,
def:/^ *\[([^\]]+)\]: *<?([^\s>]+)>?(?: +["(]([^\n]+)[")])? *(?:\n+|$)/,table:n,paragraph:/^((?:[^\n]+\n?(?!hr|heading|lheading|blockquote|tag|def))+)\n*/,text:/^[^\n]+/,bullet:/(?:[*+-]|\d+\.)/,item:/^( *)(bull) [^\n]*(?:\n(?!\1bull )[^\n]*)*/};m.item=d(m.item,"gm")(/bull/g,m.bullet)();m.list=d(m.list)(/bull/g,m.bullet)("hr",/\n+(?=(?: *[-*_]){3,} *(?:\n+|$))/)();m._tag="(?!(?:a|em|strong|small|s|cite|q|dfn|abbr|data|time|code|var|samp|kbd|sub|sup|i|b|u|mark|ruby|rt|rp|bdi|bdo|span|br|wbr|ins|del|img)\\b)\\w+(?!:/|@)\\b";
m.html=d(m.html)("comment",/\x3c!--[\s\S]*?--\x3e/)("closed",/<(tag)[\s\S]+?<\/\1>/)("closing",/<tag(?:"[^"]*"|'[^']*'|[^'">])*?>/)(/tag/g,m._tag)();m.paragraph=d(m.paragraph)("hr",m.hr)("heading",m.heading)("lheading",m.lheading)("blockquote",m.blockquote)("tag","<"+m._tag)("def",m.def)();m.normal=g({},m);m.gfm=g({},m.normal,{fences:/^ *(`{3,}|~{3,}) *(\S+)? *\n([\s\S]+?)\s*\1 *(?:\n+|$)/,paragraph:/^/});m.gfm.paragraph=d(m.paragraph)("(?!","(?!"+m.gfm.fences.source.replace("\\1","\\2")+"|")();m.tables=
g({},m.gfm,{nptable:/^ *(\S.*\|.*)\n *([-:]+ *\|[-| :]*)\n((?:.*\|.*(?:\n|$))*)\n*/,table:/^ *\|(.+)\n *\|( *[-:]+[-| :]*)\n((?: *\|.*(?:\n|$))*)\n*/});c.rules=m;c.lex=function(a,d){return(new c(d)).lex(a)};c.prototype.lex=function(a){a=a.replace(/\r\n|\r/g,"\n").replace(/\t/g,"    ").replace(/\u00a0/g," ").replace(/\u2424/g,"\n");return this.token(a,!0)};c.prototype.token=function(a,c){a=a.replace(/^ +$/gm,"");for(var d,e,h,g,k,f,p;a;){if(h=this.rules.newline.exec(a))a=a.substring(h[0].length),1<
h[0].length&&this.tokens.push({type:"space"});if(h=this.rules.code.exec(a))a=a.substring(h[0].length),h=h[0].replace(/^ {4}/gm,""),this.tokens.push({type:"code",text:this.options.pedantic?h:h.replace(/\n+$/,"")});else if(h=this.rules.fences.exec(a))a=a.substring(h[0].length),this.tokens.push({type:"code",lang:h[2],text:h[3]});else if(h=this.rules.heading.exec(a))a=a.substring(h[0].length),this.tokens.push({type:"heading",depth:h[1].length,text:h[2]});else if(c&&(h=this.rules.nptable.exec(a))){a=a.substring(h[0].length);
k={type:"table",header:h[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:h[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:h[3].replace(/\n$/,"").split("\n")};for(f=0;f<k.align.length;f++)/^ *-+: *$/.test(k.align[f])?k.align[f]="right":/^ *:-+: *$/.test(k.align[f])?k.align[f]="center":/^ *:-+ *$/.test(k.align[f])?k.align[f]="left":k.align[f]=null;for(f=0;f<k.cells.length;f++)k.cells[f]=k.cells[f].split(/ *\| */);this.tokens.push(k)}else if(h=this.rules.lheading.exec(a))a=a.substring(h[0].length),
this.tokens.push({type:"heading",depth:"="===h[2]?1:2,text:h[1]});else if(h=this.rules.hr.exec(a))a=a.substring(h[0].length),this.tokens.push({type:"hr"});else if(h=this.rules.blockquote.exec(a))a=a.substring(h[0].length),this.tokens.push({type:"blockquote_start"}),h=h[0].replace(/^ *> ?/gm,""),this.token(h,c),this.tokens.push({type:"blockquote_end"});else if(h=this.rules.list.exec(a)){a=a.substring(h[0].length);g=h[2];this.tokens.push({type:"list_start",ordered:1<g.length});h=h[0].match(this.rules.item);
d=!1;p=h.length;for(f=0;f<p;f++)k=h[f],e=k.length,k=k.replace(/^ *([*+-]|\d+\.) +/,""),~k.indexOf("\n ")&&(e-=k.length,k=this.options.pedantic?k.replace(/^ {1,4}/gm,""):k.replace(RegExp("^ {1,"+e+"}","gm"),"")),this.options.smartLists&&f!==p-1&&(e=m.bullet.exec(h[f+1])[0],g===e||1<g.length&&1<e.length||(a=h.slice(f+1).join("\n")+a,f=p-1)),e=d||/\n\n(?!\s*$)/.test(k),f!==p-1&&(d="\n"===k[k.length-1],e||(e=d)),this.tokens.push({type:e?"loose_item_start":"list_item_start"}),this.token(k,!1),this.tokens.push({type:"list_item_end"});
this.tokens.push({type:"list_end"})}else if(h=this.rules.html.exec(a))a=a.substring(h[0].length),this.tokens.push({type:this.options.sanitize?"paragraph":"html",pre:"pre"===h[1]||"script"===h[1],text:h[0]});else if(c&&(h=this.rules.def.exec(a)))a=a.substring(h[0].length),this.tokens.links[h[1].toLowerCase()]={href:h[2],title:h[3]};else if(c&&(h=this.rules.table.exec(a))){a=a.substring(h[0].length);k={type:"table",header:h[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:h[2].replace(/^ *|\| *$/g,
"").split(/ *\| */),cells:h[3].replace(/(?: *\| *)?\n$/,"").split("\n")};for(f=0;f<k.align.length;f++)/^ *-+: *$/.test(k.align[f])?k.align[f]="right":/^ *:-+: *$/.test(k.align[f])?k.align[f]="center":/^ *:-+ *$/.test(k.align[f])?k.align[f]="left":k.align[f]=null;for(f=0;f<k.cells.length;f++)k.cells[f]=k.cells[f].replace(/^ *\| *| *\| *$/g,"").split(/ *\| */);this.tokens.push(k)}else if(c&&(h=this.rules.paragraph.exec(a)))a=a.substring(h[0].length),this.tokens.push({type:"paragraph",text:"\n"===h[1][h[1].length-
1]?h[1].slice(0,-1):h[1]});else if(h=this.rules.text.exec(a))a=a.substring(h[0].length),this.tokens.push({type:"text",text:h[0]});else if(a)throw Error("Infinite loop on byte: "+a.charCodeAt(0));}return this.tokens};var t={escape:/^\\([\\`*{}\[\]()#+\-.!_>])/,autolink:/^<([^ >]+(@|:\/)[^ >]+)>/,url:n,tag:/^\x3c!--[\s\S]*?--\x3e|^<\/?\w+(?:"[^"]*"|'[^']*'|[^'">])*?>/,link:/^!?\[(inside)\]\(href\)/,reflink:/^!?\[(inside)\]\s*\[([^\]]*)\]/,nolink:/^!?\[((?:\[[^\]]*\]|[^\[\]])*)\]/,strong:/^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,
em:/^\b_((?:__|[\s\S])+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,code:/^(`+)\s*([\s\S]*?[^`])\s*\1(?!`)/,br:/^ {2,}\n(?!\s*$)/,del:n,text:/^[\s\S]+?(?=[\\<!\[_*`]| {2,}\n|$)/,_inside:/(?:\[[^\]]*\]|[^\]]|\](?=[^\[]*\]))*/,_href:/\s*<?([^\s]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*/};t.link=d(t.link)("inside",t._inside)("href",t._href)();t.reflink=d(t.reflink)("inside",t._inside)();t.normal=g({},t);t.pedantic=g({},t.normal,{strong:/^__(?=\S)([\s\S]*?\S)__(?!_)|^\*\*(?=\S)([\s\S]*?\S)\*\*(?!\*)/,em:/^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)/});
t.gfm=g({},t.normal,{escape:d(t.escape)("])","~|])")(),url:/^(https?:\/\/[^\s<]+[^<.,:;"')\]\s])/,del:/^~~(?=\S)([\s\S]*?\S)~~/,text:d(t.text)("]|","~]|")("|","|https?://|")()});t.breaks=g({},t.gfm,{br:d(t.br)("{2,}","*")(),text:d(t.gfm.text)("{2,}","*")()});l.rules=t;l.output=function(a,c,d){return(new l(c,d)).output(a)};l.prototype.output=function(a){for(var c="",d,e;a;)if(e=this.rules.escape.exec(a))a=a.substring(e[0].length),c+=e[1];else if(e=this.rules.autolink.exec(a))a=a.substring(e[0].length),
"@"===e[2]?(d=":"===e[1][6]?this.mangle(e[1].substring(7)):this.mangle(e[1]),e=this.mangle("mailto:")+d):e=d=f(e[1]),c+='<a href="'+e+'">'+d+"</a>";else if(e=this.rules.url.exec(a))a=a.substring(e[0].length),e=d=f(e[1]),c+='<a href="'+e+'">'+d+"</a>";else if(e=this.rules.tag.exec(a))a=a.substring(e[0].length),c+=this.options.sanitize?f(e[0]):e[0];else if(e=this.rules.link.exec(a))a=a.substring(e[0].length),c+=this.outputLink(e,{href:e[2],title:e[3]});else if((e=this.rules.reflink.exec(a))||(e=this.rules.nolink.exec(a)))a=
a.substring(e[0].length),d=(e[2]||e[1]).replace(/\s+/g," "),(d=this.links[d.toLowerCase()])&&d.href?c+=this.outputLink(e,d):(c+=e[0][0],a=e[0].substring(1)+a);else if(e=this.rules.strong.exec(a))a=a.substring(e[0].length),c+="<strong>"+this.output(e[2]||e[1])+"</strong>";else if(e=this.rules.em.exec(a))a=a.substring(e[0].length),c+="<em>"+this.output(e[2]||e[1])+"</em>";else if(e=this.rules.code.exec(a))a=a.substring(e[0].length),c+="<code>"+f(e[2],!0)+"</code>";else if(e=this.rules.br.exec(a))a=
a.substring(e[0].length),c+="<br>";else if(e=this.rules.del.exec(a))a=a.substring(e[0].length),c+="<del>"+this.output(e[1])+"</del>";else if(e=this.rules.text.exec(a))a=a.substring(e[0].length),c+=f(this.smartypants(e[0]));else if(a)throw Error("Infinite loop on byte: "+a.charCodeAt(0));return c};l.prototype.outputLink=function(a,c){return"!"!==a[0][0]?'<a href="'+f(c.href)+'"'+(c.title?' title="'+f(c.title)+'"':"")+">"+this.output(a[1])+"</a>":'<img src="'+f(c.href)+'" alt="'+f(a[1])+'"'+(c.title?
' title="'+f(c.title)+'"':"")+">"};l.prototype.smartypants=function(a){return this.options.smartypants?a.replace(/--/g,"\u2014").replace(/'([^']*)'/g,"\u2018$1\u2019").replace(/"([^"]*)"/g,"\u201c$1\u201d").replace(/\.{3}/g,"\u2026"):a};l.prototype.mangle=function(a){for(var c="",d=a.length,e=0,h;e<d;e++)h=a.charCodeAt(e),0.5<Math.random()&&(h="x"+h.toString(16)),c+="&#"+h+";";return c};u.parse=function(a,c){return(new u(c)).parse(a)};u.prototype.parse=function(a){this.inline=new l(a.links,this.options);
this.tokens=a.reverse();for(a="";this.next();)a+=this.tok();return a};u.prototype.next=function(){return this.token=this.tokens.pop()};u.prototype.peek=function(){return this.tokens[this.tokens.length-1]||0};u.prototype.parseText=function(){for(var a=this.token.text;"text"===this.peek().type;)a+="\n"+this.next().text;return this.inline.output(a)};u.prototype.tok=function(){switch(this.token.type){case "space":return"";case "hr":return"<hr>\n";case "heading":return"<h"+this.token.depth+">"+this.inline.output(this.token.text)+
"</h"+this.token.depth+">\n";case "code":if(this.options.highlight){var a=this.options.highlight(this.token.text,this.token.lang);null!=a&&a!==this.token.text&&(this.token.escaped=!0,this.token.text=a)}this.token.escaped||(this.token.text=f(this.token.text,!0));return"<pre><code"+(this.token.lang?' class="'+this.options.langPrefix+this.token.lang+'"':"")+">"+this.token.text+"</code></pre>\n";case "table":var c,d,e,h,a="<thead>\n<tr>\n";for(d=0;d<this.token.header.length;d++)c=this.inline.output(this.token.header[d]),
a+=this.token.align[d]?'<th align="'+this.token.align[d]+'">'+c+"</th>\n":"<th>"+c+"</th>\n";a+="</tr>\n</thead>\n<tbody>\n";for(d=0;d<this.token.cells.length;d++){c=this.token.cells[d];a+="<tr>\n";for(h=0;h<c.length;h++)e=this.inline.output(c[h]),a+=this.token.align[h]?'<td align="'+this.token.align[h]+'">'+e+"</td>\n":"<td>"+e+"</td>\n";a+="</tr>\n"}a+="</tbody>\n";return"<table>\n"+a+"</table>\n";case "blockquote_start":for(a="";"blockquote_end"!==this.next().type;)a+=this.tok();return"<blockquote>\n"+
a+"</blockquote>\n";case "list_start":d=this.token.ordered?"ol":"ul";for(a="";"list_end"!==this.next().type;)a+=this.tok();return"<"+d+">\n"+a+"</"+d+">\n";case "list_item_start":for(a="";"list_item_end"!==this.next().type;)a+="text"===this.token.type?this.parseText():this.tok();return"<li>"+a+"</li>\n";case "loose_item_start":for(a="";"list_item_end"!==this.next().type;)a+=this.tok();return"<li>"+a+"</li>\n";case "html":return this.token.pre||this.options.pedantic?this.token.text:this.inline.output(this.token.text);
case "paragraph":return"<p>"+this.inline.output(this.token.text)+"</p>\n";case "text":return"<p>"+this.parseText()+"</p>\n"}};n.exec=n;p.options=p.setOptions=function(a){g(p.defaults,a);return p};p.defaults={gfm:!0,tables:!0,breaks:!1,pedantic:!1,sanitize:!1,smartLists:!1,silent:!1,highlight:null,langPrefix:"lang-",smartypants:!1};p.Parser=u;p.parser=u.parse;p.Lexer=c;p.lexer=c.lex;p.InlineLexer=l;p.inlineLexer=l.output;p.parse=p;"object"===typeof exports?module.exports=p:"function"===typeof define&&
define.amd?define(function(){return p}):this.marked=p}).call(function(){return this||("undefined"!==typeof window?window:global)}());
var utf8=function(){return{stringToBytes:function(c){for(var l=[],u=c.length,f=0,d,n;f<u;){d=c.charCodeAt(f++);if(55296<=d&&56319>=d){if(f===u)throw Error("Invalid format");n=c.charCodeAt(f++);if(!(56320<=n&&57343>=n))throw Error("Invalid format");d=(d-55296<<10)+(n-56320)+65536}128>d?l.push(d):(2048>d?l.push(192|d>>6):(65536>d?l.push(224|d>>12):(l.push(240|d>>18),l.push(128|d>>12&63)),l.push(128|d>>6&63)),l.push(128|d&63))}return l},bytesToString:function(c){for(var l="",u=c.length,f=0,d;f<u;){d=
c[f++];d=128>d?d:6===d>>5?(d&31)<<6|c[f++]&63:14===d>>4?(d&15)<<12|(c[f++]&63)<<6|c[f++]&63:(d&7)<<18|(c[f++]&63)<<12|(c[f++]&63)<<6|c[f++]&63;var n=void 0,g=void 0;65536>d?d=String.fromCharCode(d):(n=(d-65536>>10)+55296,g=(d&1023)+56320,d=String.fromCharCode(n,g));l+=d}return l}}}(),CryptoJS=CryptoJS||function(c,l){var u={},f=u.lib={},d=function(){},n=f.Base={extend:function(a){d.prototype=this;var c=new d;a&&c.mixIn(a);c.hasOwnProperty("init")||(c.init=function(){c.$super.init.apply(this,arguments)});
c.init.prototype=c;c.$super=this;return c},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var c in a)a.hasOwnProperty(c)&&(this[c]=a[c]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.init.prototype.extend(this)}},g=f.WordArray=n.extend({init:function(a,c){a=this.words=a||[];this.sigBytes=c!=l?c:4*a.length},toString:function(a){return(a||m).stringify(this)},concat:function(a){var c=this.words,
d=a.words,k=this.sigBytes;a=a.sigBytes;this.clamp();if(k%4)for(var f=0;f<a;f++)c[k+f>>>2]|=(d[f>>>2]>>>24-8*(f%4)&255)<<24-8*((k+f)%4);else if(65535<d.length)for(f=0;f<a;f+=4)c[k+f>>>2]=d[f>>>2];else c.push.apply(c,d);this.sigBytes+=a;return this},clamp:function(){var a=this.words,d=this.sigBytes;a[d>>>2]&=4294967295<<32-8*(d%4);a.length=c.ceil(d/4)},clone:function(){var a=n.clone.call(this);a.words=this.words.slice(0);return a},random:function(a){for(var d=[],f=0;f<a;f+=4)d.push(4294967296*c.random()|
0);return new g.init(d,a)}}),p=u.enc={},m=p.Hex={stringify:function(a){var c=a.words;a=a.sigBytes;for(var d=[],f=0;f<a;f++){var g=c[f>>>2]>>>24-8*(f%4)&255;d.push((g>>>4).toString(16));d.push((g&15).toString(16))}return d.join("")},parse:function(a){for(var c=a.length,d=[],f=0;f<c;f+=2)d[f>>>3]|=parseInt(a.substr(f,2),16)<<24-4*(f%8);return new g.init(d,c/2)}},t=p.Latin1={stringify:function(a){var c=a.words;a=a.sigBytes;for(var d=[],f=0;f<a;f++)d.push(String.fromCharCode(c[f>>>2]>>>24-8*(f%4)&255));
return d.join("")},parse:function(a){for(var c=a.length,d=[],f=0;f<c;f++)d[f>>>2]|=(a.charCodeAt(f)&255)<<24-8*(f%4);return new g.init(d,c)}},a=p.Utf8={stringify:function(a){try{return decodeURIComponent(escape(t.stringify(a)))}catch(c){throw Error("Malformed UTF-8 data");}},parse:function(a){return t.parse(unescape(encodeURIComponent(a)))}},s=f.BufferedBlockAlgorithm=n.extend({reset:function(){this._data=new g.init;this._nDataBytes=0},_append:function(c){"string"==typeof c&&(c=a.parse(c));this._data.concat(c);
this._nDataBytes+=c.sigBytes},_process:function(a){var d=this._data,f=d.words,k=d.sigBytes,m=this.blockSize,p=k/(4*m),p=a?c.ceil(p):c.max((p|0)-this._minBufferSize,0);a=p*m;k=c.min(4*a,k);if(a){for(var l=0;l<a;l+=m)this._doProcessBlock(f,l);l=f.splice(0,a);d.sigBytes-=k}return new g.init(l,k)},clone:function(){var a=n.clone.call(this);a._data=this._data.clone();return a},_minBufferSize:0});f.Hasher=s.extend({cfg:n.extend(),init:function(a){this.cfg=this.cfg.extend(a);this.reset()},reset:function(){s.reset.call(this);
this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);return this._doFinalize()},blockSize:16,_createHelper:function(a){return function(c,d){return(new a.init(d)).finalize(c)}},_createHmacHelper:function(a){return function(c,d){return(new r.HMAC.init(a,d)).finalize(c)}}});var r=u.algo={};return u}(Math);
(function(c){for(var l=CryptoJS,u=l.lib,f=u.WordArray,d=u.Hasher,u=l.algo,n=[],g=[],p=function(a){return 4294967296*(a-(a|0))|0},m=2,t=0;64>t;){var a;a:{a=m;for(var s=c.sqrt(a),r=2;r<=s;r++)if(!(a%r)){a=!1;break a}a=!0}a&&(8>t&&(n[t]=p(c.pow(m,0.5))),g[t]=p(c.pow(m,1/3)),t++);m++}var e=[],u=u.SHA256=d.extend({_doReset:function(){this._hash=new f.init(n.slice(0))},_doProcessBlock:function(a,c){for(var d=this._hash.words,f=d[0],m=d[1],p=d[2],l=d[3],n=d[4],b=d[5],t=d[6],s=d[7],r=0;64>r;r++){if(16>r)e[r]=
a[c+r]|0;else{var u=e[r-15],E=e[r-2];e[r]=((u<<25|u>>>7)^(u<<14|u>>>18)^u>>>3)+e[r-7]+((E<<15|E>>>17)^(E<<13|E>>>19)^E>>>10)+e[r-16]}u=s+((n<<26|n>>>6)^(n<<21|n>>>11)^(n<<7|n>>>25))+(n&b^~n&t)+g[r]+e[r];E=((f<<30|f>>>2)^(f<<19|f>>>13)^(f<<10|f>>>22))+(f&m^f&p^m&p);s=t;t=b;b=n;n=l+u|0;l=p;p=m;m=f;f=u+E|0}d[0]=d[0]+f|0;d[1]=d[1]+m|0;d[2]=d[2]+p|0;d[3]=d[3]+l|0;d[4]=d[4]+n|0;d[5]=d[5]+b|0;d[6]=d[6]+t|0;d[7]=d[7]+s|0},_doFinalize:function(){var a=this._data,d=a.words,e=8*this._nDataBytes,f=8*a.sigBytes;
d[f>>>5]|=128<<24-f%32;d[(f+64>>>9<<4)+14]=c.floor(e/4294967296);d[(f+64>>>9<<4)+15]=e;a.sigBytes=4*d.length;this._process();return this._hash},clone:function(){var a=d.clone.call(this);a._hash=this._hash.clone();return a}});l.SHA256=d._createHelper(u);l.HmacSHA256=d._createHmacHelper(u)})(Math);
(function(c){for(var l=CryptoJS,u=l.lib,f=u.WordArray,d=u.Hasher,u=l.algo,n=[],g=[],p=function(a){return 4294967296*(a-(a|0))|0},m=2,t=0;64>t;){var a;a:{a=m;for(var s=c.sqrt(a),r=2;r<=s;r++)if(!(a%r)){a=!1;break a}a=!0}a&&(8>t&&(n[t]=p(c.pow(m,0.5))),g[t]=p(c.pow(m,1/3)),t++);m++}var e=[],u=u.SHA256=d.extend({_doReset:function(){this._hash=new f.init(n.slice(0))},_doProcessBlock:function(a,c){for(var d=this._hash.words,f=d[0],m=d[1],p=d[2],l=d[3],n=d[4],b=d[5],t=d[6],s=d[7],r=0;64>r;r++){if(16>r)e[r]=
a[c+r]|0;else{var u=e[r-15],E=e[r-2];e[r]=((u<<25|u>>>7)^(u<<14|u>>>18)^u>>>3)+e[r-7]+((E<<15|E>>>17)^(E<<13|E>>>19)^E>>>10)+e[r-16]}u=s+((n<<26|n>>>6)^(n<<21|n>>>11)^(n<<7|n>>>25))+(n&b^~n&t)+g[r]+e[r];E=((f<<30|f>>>2)^(f<<19|f>>>13)^(f<<10|f>>>22))+(f&m^f&p^m&p);s=t;t=b;b=n;n=l+u|0;l=p;p=m;m=f;f=u+E|0}d[0]=d[0]+f|0;d[1]=d[1]+m|0;d[2]=d[2]+p|0;d[3]=d[3]+l|0;d[4]=d[4]+n|0;d[5]=d[5]+b|0;d[6]=d[6]+t|0;d[7]=d[7]+s|0},_doFinalize:function(){var a=this._data,d=a.words,e=8*this._nDataBytes,f=8*a.sigBytes;
d[f>>>5]|=128<<24-f%32;d[(f+64>>>9<<4)+14]=c.floor(e/4294967296);d[(f+64>>>9<<4)+15]=e;a.sigBytes=4*d.length;this._process();return this._hash},clone:function(){var a=d.clone.call(this);a._hash=this._hash.clone();return a}});l.SHA256=d._createHelper(u);l.HmacSHA256=d._createHmacHelper(u)})(Math);
(function(){var c=CryptoJS,l=c.enc.Utf8;c.algo.HMAC=c.lib.Base.extend({init:function(c,f){c=this._hasher=new c.init;"string"==typeof f&&(f=l.parse(f));var d=c.blockSize,n=4*d;f.sigBytes>n&&(f=c.finalize(f));f.clamp();for(var g=this._oKey=f.clone(),p=this._iKey=f.clone(),m=g.words,t=p.words,a=0;a<d;a++)m[a]^=1549556828,t[a]^=909522486;g.sigBytes=p.sigBytes=n;this.reset()},reset:function(){var c=this._hasher;c.reset();c.update(this._iKey)},update:function(c){this._hasher.update(c);return this},finalize:function(c){var f=
this._hasher;c=f.finalize(c);f.reset();return f.finalize(this._oKey.clone().concat(c))}})})();
+function(c){var l=function(c,d){this.type=this.options=this.enabled=this.timeout=this.hoverState=this.$element=null;this.init("tooltip",c,d)};l.DEFAULTS={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:!1,container:!1};l.prototype.init=function(f,d,n){this.enabled=!0;this.type=f;this.$element=c(d);this.options=this.getOptions(n);f=this.options.trigger.split(" ");
for(d=f.length;d--;)if(n=f[d],"click"==n)this.$element.on("click."+this.type,this.options.selector,c.proxy(this.toggle,this));else if("manual"!=n){var g="hover"==n?"mouseleave":"blur";this.$element.on(("hover"==n?"mouseenter":"focus")+"."+this.type,this.options.selector,c.proxy(this.enter,this));this.$element.on(g+"."+this.type,this.options.selector,c.proxy(this.leave,this))}this.options.selector?this._options=c.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};l.prototype.getDefaults=
function(){return l.DEFAULTS};l.prototype.getOptions=function(f){f=c.extend({},this.getDefaults(),this.$element.data(),f);f.delay&&"number"==typeof f.delay&&(f.delay={show:f.delay,hide:f.delay});return f};l.prototype.enter=function(f){var d=this.getDefaults(),n={};this._options&&c.each(this._options,function(c,f){d[c]!=f&&(n[c]=f)});var g=f instanceof this.constructor?f:c(f.currentTarget)[this.type](n).data("bs."+this.type);if(!g.options.delay||!g.options.delay.show)return g.show();clearTimeout(this.timeout);
g.hoverState="in";this.timeout=setTimeout(function(){"in"==g.hoverState&&g.show()},g.options.delay.show)};l.prototype.leave=function(f){var d=f instanceof this.constructor?f:c(f.currentTarget)[this.type](this._options).data("bs."+this.type);clearTimeout(this.timeout);if(!d.options.delay||!d.options.delay.hide)return d.hide();d.hoverState="out";this.timeout=setTimeout(function(){"out"==d.hoverState&&d.hide()},d.options.delay.hide)};l.prototype.show=function(){var f=c.Event("show.bs."+this.type);if(this.hasContent()&&
this.enabled&&(this.$element.trigger(f),!f.isDefaultPrevented())){var d=this.tip();this.setContent();this.options.animation&&d.addClass("fade");f="function"==typeof this.options.placement?this.options.placement.call(this,d[0],this.$element[0]):this.options.placement;d.detach().css({top:0,left:0,display:"block"});this.options.container?d.appendTo(this.options.container):d.insertAfter(this.$element);var n,g=this.getPosition(),p=d[0].offsetWidth,d=d[0].offsetHeight;switch(f){case "bottom":n={top:g.top+
g.height,left:g.left+g.width/2-p/2};break;case "top":n={top:g.top-d,left:g.left+g.width/2-p/2};break;case "left":n={top:g.top+g.height/2-d/2,left:g.left-p};break;case "right":n={top:g.top+g.height/2-d/2,left:g.left+g.width}}this.applyPlacement(n,f);this.$element.trigger("shown.bs."+this.type)}};l.prototype.applyPlacement=function(c,d){var n,g=this.tip(),p=g[0].offsetWidth,m=g[0].offsetHeight;g.offset(c).addClass(d).addClass("in");var l=g[0].offsetWidth,a=g[0].offsetHeight;"top"==d&&a!=m&&(n=!0,c.top=
c.top+m-a);"bottom"==d||"top"==d?(m=0,0>c.left&&(m=-2*c.left,c.left=0,g.offset(c),l=g[0].offsetWidth),this.replaceArrow(m-p+l,l,"left")):this.replaceArrow(a-m,a,"top");n&&g.offset(c)};l.prototype.replaceArrow=function(c,d,l){this.arrow().css(l,c?50*(1-c/d)+"%":"")};l.prototype.setContent=function(){var c=this.tip(),d=this.getTitle();c.find(".tooltip-inner")[this.options.html?"html":"text"](d);c.removeClass("fade in top bottom left right")};l.prototype.hide=function(){function f(){var f=setTimeout(function(){d.off(c.support.transition.end).detach()},
500);d.one(c.support.transition.end,function(){clearTimeout(f);d.detach()})}var d=this.tip(),l=c.Event("hide.bs."+this.type);this.$element.trigger(l);if(!l.isDefaultPrevented())return d.removeClass("in"),c.support.transition&&this.$tip.hasClass("fade")?f():d.detach(),this.$element.trigger("hidden.bs."+this.type),this};l.prototype.fixTitle=function(){var c=this.$element;(c.attr("title")||"string"!=typeof c.attr("data-original-title"))&&c.attr("data-original-title",c.attr("title")||"").attr("title",
"")};l.prototype.hasContent=function(){return this.getTitle()};l.prototype.getPosition=function(){var f=this.$element[0];return c.extend({},"function"==typeof f.getBoundingClientRect?f.getBoundingClientRect():{width:f.offsetWidth,height:f.offsetHeight},this.$element.offset())};l.prototype.getTitle=function(){var c=this.$element,d=this.options;return c.attr("data-original-title")||("function"==typeof d.title?d.title.call(c[0]):d.title)};l.prototype.tip=function(){return this.$tip=this.$tip||c(this.options.template)};
l.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")};l.prototype.validate=function(){this.$element[0].parentNode||(this.hide(),this.options=this.$element=null)};l.prototype.enable=function(){this.enabled=!0};l.prototype.disable=function(){this.enabled=!1};l.prototype.toggleEnabled=function(){this.enabled=!this.enabled};l.prototype.toggle=function(f){f=f?c(f.currentTarget)[this.type](this._options).data("bs."+this.type):this;f.tip().hasClass("in")?f.leave(f):
f.enter(f)};l.prototype.destroy=function(){this.hide().$element.off("."+this.type).removeData("bs."+this.type)};var u=c.fn.tooltip;c.fn.tooltip=function(f){return this.each(function(){var d=c(this),n=d.data("bs.tooltip"),g="object"==typeof f&&f;n||d.data("bs.tooltip",n=new l(this,g));if("string"==typeof f)n[f]()})};c.fn.tooltip.Constructor=l;c.fn.tooltip.noConflict=function(){c.fn.tooltip=u;return this}}(window.jQuery);
+function(c){var l=function(d,f){this.options=f;this.$element=c(d).delegate('[data-dismiss="modal"]',"click.dismiss.modal",c.proxy(this.hide,this));this.$backdrop=this.isShown=null;this.options.remote&&this.$element.find(".modal-body").load(this.options.remote)};l.DEFAULTS={backdrop:!0,keyboard:!0,show:!0};l.prototype.toggle=function(){return this[this.isShown?"hide":"show"]()};l.prototype.show=function(){var d=this,f=c.Event("show.bs.modal");this.$element.trigger(f);this.isShown||f.isDefaultPrevented()||
(this.isShown=!0,this.escape(),this.backdrop(function(){var f=c.support.transition&&d.$element.hasClass("fade");d.$element.parent().length||d.$element.appendTo(document.body);d.$element.show();f&&d.$element[0].offsetWidth;d.$element.addClass("in").attr("aria-hidden",!1);d.enforceFocus();f?d.$element.one(c.support.transition.end,function(){d.$element.focus().trigger("shown.bs.modal")}):d.$element.focus().trigger("shown.bs.modal")}))};l.prototype.hide=function(d){d&&d.preventDefault();d=c.Event("hide.bs.modal");
this.$element.trigger(d);this.isShown&&!d.isDefaultPrevented()&&(this.isShown=!1,this.escape(),c(document).off("focusin.bs.modal"),this.$element.removeClass("in").attr("aria-hidden",!0),c.support.transition&&this.$element.hasClass("fade")?this.hideWithTransition():this.hideModal())};l.prototype.enforceFocus=function(){c(document).off("focusin.bs.modal").on("focusin.bs.modal",c.proxy(function(c){this.$element[0]===c.target||this.$element.has(c.target).length||this.$element.focus()},this))};l.prototype.escape=
function(){if(this.isShown&&this.options.keyboard)this.$element.on("keyup.dismiss.bs.modal",c.proxy(function(c){27==c.which&&this.hide()},this));else this.isShown||this.$element.off("keyup.dismiss.bs.modal")};l.prototype.hideWithTransition=function(){var d=this,f=setTimeout(function(){d.$element.off(c.support.transition.end);d.hideModal()},500);this.$element.one(c.support.transition.end,function(){clearTimeout(f);d.hideModal()})};l.prototype.hideModal=function(){var c=this;this.$element.hide();this.backdrop(function(){c.removeBackdrop();
c.$element.trigger("hidden.bs.modal")})};l.prototype.removeBackdrop=function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};l.prototype.backdrop=function(d){var f=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var g=c.support.transition&&f;this.$backdrop=c('<div class="modal-backdrop '+f+'" />').appendTo(document.body);this.$backdrop.click("static"==this.options.backdrop?c.proxy(this.$element[0].focus,this.$element[0]):c.proxy(this.hide,this));g&&
this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");d&&(g?this.$backdrop.one(c.support.transition.end,d):d())}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),c.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(c.support.transition.end,d):d()):d&&d()};var u=c.fn.modal;c.fn.modal=function(d){return this.each(function(){var f=c(this),g=f.data("bs.modal"),p=c.extend({},l.DEFAULTS,f.data(),"object"==typeof d&&d);g||f.data("bs.modal",g=new l(this,p));if("string"==
typeof d)g[d]();else p.show&&g.show()})};c.fn.modal.Constructor=l;c.fn.modal.noConflict=function(){c.fn.modal=u;return this};c(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(d){var f=c(this),g=f.attr("href"),l=c(f.attr("data-target")||g&&g.replace(/.*(?=#[^\s]+$)/,"")),g=l.data("modal")?"toggle":c.extend({remote:!/#/.test(g)&&g},l.data(),f.data());d.preventDefault();l.modal(g).one("hide",function(){f.focus()})});var f=c(document.body).on("bs.modal.shown",".modal",function(){f.addClass("modal-open")}).on("bs.modal.hidden",
".modal",function(){f.removeClass("modal-open")})}(window.jQuery);
+function(c){function l(){c(f).remove();c(d).each(function(d){var f=u(c(this));f.hasClass("open")&&(f.trigger(d=c.Event("hide.bs.dropdown")),d.isDefaultPrevented()||f.removeClass("open").trigger("hidden.bs.dropdown"))})}function u(d){var f=d.attr("data-target");f||(f=(f=d.attr("href"))&&/#/.test(f)&&f.replace(/.*(?=#[^\s]*$)/,""));return(f=f&&c(f))&&f.length?f:d.parent()}var f=".dropdown-backdrop",d="[data-toggle=dropdown]",n=function(d){c(d).on("click.bs.dropdown",this.toggle)};n.prototype.toggle=
function(d){var f=c(this);if(!f.is(".disabled, :disabled")){var g=u(f);d=g.hasClass("open");l();if(!d){if("ontouchstart"in document.documentElement)c('<div class="dropdown-backdrop"/>').insertBefore(c(this)).on("click",l);g.trigger(d=c.Event("show.bs.dropdown"));if(d.isDefaultPrevented())return;g.toggleClass("open").trigger("shown.bs.dropdown")}f.focus();return!1}};n.prototype.keydown=function(f){if(/(38|40|27)/.test(f.keyCode)){var g=c(this);f.preventDefault();f.stopPropagation();if(!g.is(".disabled, :disabled")){var l=
u(g),a=l.hasClass("open");if(!a||a&&27==f.keyCode)return 27==f.which&&l.find(d).focus(),g.click();g=c("[role=menu] li:not(.divider):visible a",l);g.length&&(l=g.index(g.filter(":focus")),38==f.keyCode&&0<l&&l--,40==f.keyCode&&l<g.length-1&&l++,~l||(l=0),g.eq(l).focus())}}};var g=c.fn.dropdown;c.fn.dropdown=function(d){return this.each(function(){var f=c(this),g=f.data("dropdown");g||f.data("dropdown",g=new n(this));"string"==typeof d&&g[d].call(f)})};c.fn.dropdown.Constructor=n;c.fn.dropdown.noConflict=
function(){c.fn.dropdown=g;return this};c(document).on("click.bs.dropdown.data-api",l).on("click.bs.dropdown.data-api",".dropdown form",function(c){c.stopPropagation()}).on("click.bs.dropdown.data-api",d,n.prototype.toggle).on("keydown.bs.dropdown.data-api",d+", [role=menu]",n.prototype.keydown)}(window.jQuery);